### ISSUE TITLE
Adding values to README?

### ISSUE THREAD

**Issue by Aracki** [hashicorp/vault-helm#106]
1. I suppose we will need **_values_** table in README like the every other stable helm chart out there.

2. I think the `Testing` section should be moved to the Wiki.

**Comment by jasonodonnell** [comment]
Hi @Aracki, documentation of all the values can be found here (link is at the top of the README): https://www.vaultproject.io/docs/platform/k8s/helm.html#configuration-values-.

Thanks for the suggestion, we'll take it into consideration! 👍

**Comment by Aracki** [comment]
Thanks, @jasonodonnell. 👍
