### ISSUE TITLE
Vault pod not coming up

### ISSUE THREAD

**Issue by amanchourasiya** [hashicorp/vault-helm#112]
After following all the steps in readme. and creating storage class and persistent volume getting this error
Events:
  Type       Reason                Age                            From                         Message
  ----       ------                ----                           ----                         -------
  Normal     WaitForFirstConsumer  <invalid> (x2 over <invalid>)  persistentvolume-controller  waiting for first consumer to be created before binding

**Comment by amanchourasiya** [comment]
Same as this https://stackoverflow.com/questions/55044486/waitforfirstconsumer-persistentvolumeclaim-waiting-for-first-consumer-to-be-crea  
 But the solution given is not working

**Comment by jasonodonnell** [comment]
Hello,

Can you provide the output to the following commands:

```bash
kubectl get storageclass
kubectl describe storageclass
kubectl get pvc
kubectl describe pvc
kubectl get pv
```

**Comment by amanchourasiya** [comment]
[root@node1-dev]# k get storageclass
NAME            PROVISIONER                    AGE
local-storage   kubernetes.io/no-provisioner   23h

[root@node1-dev]# k describe sc local-storage
Name:                  local-storage
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           kubernetes.io/no-provisioner
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>


[root@node1-dev]# kubectl get pvc
data-vault10-0                        Pending                                      local-storage   2m13s

[root@node1-dev]# k describe pvc data-vault10-0
Name:          data-vault10-0
Namespace:     default
StorageClass:  local-storage
Status:        Pending
Volume:
Labels:        app.kubernetes.io/instance=vault10
               app.kubernetes.io/name=vault
               component=server
               helm.sh/chart=vault-0.2.1
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    vault10-0
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  WaitForFirstConsumer  14s (x13 over 3m7s)  persistentvolume-controller  waiting for first consumer to be created before binding


[root@node1-dev]# k get pv
NAME       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS    REASON   AGE
local-pv   10Gi       RWO            Retain           Available           local-storage            6m24s

**Comment by amanchourasiya** [comment]
In values.yaml I made entered these values

 affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/node1

  dataStorage:
    enabled: true
    # Size of the PVC created
    size: 5Gi
    # Name of the storage class to use.  If null it will use the
    # configured default Storage Class.
    storageClass: local-storage
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce

**Comment by amanchourasiya** [comment]
Is there any other value in values.yaml we need to modify?

**Comment by imorti** [comment]
I'm having the same problem. So happy to add values etc.

**Comment by imorti** [comment]
btw, if you change   
dev: from false to true the pod comes up.

**Comment by jasonodonnell** [comment]
Dev mode auto-initializes and unseals itself, so it will show a ready status.  Standard and HA mode do not, they need to be initialized and unsealed before they become ready.

Dev mode also has no volume claims, so if there's a problem with storage, you won't see it in dev mode.

**Comment by jasonodonnell** [comment]
@amanchourasiya This issue seems to be related to the storage class being used and not Vault Helm itself.  I haven't been able to track down what the issue with the storage class is because I cannot replicate it on my end.  Can you provide more info about your environment? I'm not familiar with `local-storage` storage class.  Where can this be found?
