### ISSUE TITLE
UI Service missing `publishNotReadyAddresses`

### ISSUE THREAD

**Issue by jasonodonnell** [hashicorp/vault-helm#113]
There's a delta between the service templates.  Since we do not auto-init/auto-unseal out of the box, this should probably exist in both.

**Comment by jasonodonnell** [comment]
Fixed in #131!

**Comment by darkdragn** [comment]
Sorry about bugging you, but should publishNotReadyAddresses be on the vault-ha-ui service? In practice, if auto-unseal is not available for the deployment, it means with the loss of a single pod, we wind up with the rest endpoints and the web ui believing that vault is sealed eliminating HA by keeping the one unsealed pod in the rotation for http requests. We've been having some major headaches from it.
