### ISSUE TITLE
HA setup with consul and auto-seal using Google Cloud KMS

### ISSUE THREAD

**Issue by AClarkie** [hashicorp/vault-helm#116]
I'm following the guide and referring to the video below:
https://www.youtube.com/watch?v=_r368h-mxxs

I was hoping someone could point me at a working config and set of instructions to set up vault inside of my pre-existing GKE cluster using the vault helm chart with Google Cloud KMS for auto-unseal. The documentation for vault is great besides the helm chart HA install.

I've seen various issues across the internet for getting this working e.g:
https://github.com/hashicorp/vault-helm/issues/39

But the documentation is lacking that explains:
1) What service account need to be created
2) What needs to go in the **seal "gcpckms" {** settings
3) What extraEnvironmentVars need to be added
4) Should workload-identity be enabled
5) What secrets need to be installed before the vault helm chart

I've tried every combination and I keep hitting the following error message in my pods:
```
Error parsing Seal configuration: failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied on resource 'projects/adamtestcert/locations/global/keyRings/vault-adam/cryptoKeys/vault-adam' (or it may not exist).
```

I'm not sure how I can debug this issue further, I've confirmed my new service account has the correct permissions to access my cryptokey.

Any helm would be greatly appreciated.

**Comment by AClarkie** [comment]
I got this working by using workload-identity and then setting:

```
  extraEnvironmentVars:
    GOOGLE_REGION: global
```

**Comment by jasonodonnell** [comment]
Hey @AClarkie, glad you got it working.  I've seen this region error pop up a few times, I will add a note to the documentation about it.

I agree with you that we're lacking in the documentation department.  There is doc for setting up [Google KMS auto unseal](https://www.vaultproject.io/docs/platform/k8s/run.html#google-kms-auto-unseal) but it lacks references to the Vault doc about service account permissions required.  Additionally, I've tested workload-identity but never documented the feature do to it being in beta.  We can and will do better with the documentation.
