### ISSUE TITLE
How to backup Vault with Raft storage

### ISSUE THREAD

**Issue by msidd111** [hashicorp/vault-helm#118]
Any example of backing and restoring Vault that uses Raft storage

**Comment by jasonodonnell** [comment]
Hello @msidd111, this question is likely better on the [Vault discussion list](https://www.vaultproject.io/community).  I don't think backup/restore has been optimized yet as it's still in beta but the intended workflow is:

* Snapshot
* Bootstrap a new cluster
* Restore

You'll likely get better answers from the mailing list.
