### ISSUE TITLE
add sleep to preStop lifecycle

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/vault-helm#125]
one tip to remove 502s and 503s for customers on pod rotation is to add a sleep to the preStop lifecycle.
this extra time allows for traffic to stop routing to the pod before the SIGTERM is sent to the running process (because this removal of the routing is asynchronous)

pretty good explanation in this article: https://blog.gruntwork.io/gracefully-shutting-down-pods-in-a-kubernetes-cluster-328aecec90d

**Comment by jasonodonnell** [comment]
This is a good tip, I think we could add it.  If you would like to create a PR to add it, let me know, else I will add it in the next development cycle.
