### ISSUE TITLE
vault pod not running on minkube. 

### ISSUE THREAD

**Issue by imorti** [hashicorp/vault-helm#130]
Readiness probe failed: Key Value --- ----- Seal Type shamir Initialized false Sealed true Total Shares 0 Threshold 0 Unseal Progress 0/0 Unseal Nonce n/a Version n/a HA Enabled false

pod has unbound immediate PersistentVolumeClaims

consul cluster is up and running. 

minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad

**Comment by jasonodonnell** [comment]
@imorti It sounds like the pod came up but it isn't giving a ready status?  This is normal behavior: you need to initialize and unseal Vault before it becomes ready.

**Comment by tvoran** [comment]
Closing this one for now, let us know if you run into further issues!
