### ISSUE TITLE
Permission Bits Preventing Vault Backend PostgreSQL with Certificate-based Authentication

### ISSUE THREAD

**Issue by theonewolf** [hashicorp/vault-helm#133]
This bug report is hitting a similar issue as in the Banzai Vault Operator: https://github.com/banzaicloud/bank-vaults/issues/777

> Error initializing storage of type postgresql: failed to check for native upsert: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less

I am able to mount secrets into `/vault/userconfig`; however, I am not sure how to specify (if it's possible) mode bits with your Helm chart in `values.yaml`?

Even if we specify mode bits, I suspect that due to your `securityContext` using `fsGroup`, permissions on the private key file will forcibly become `0440`.  Right now I see this in the volume mount location within the pod's Vault container:

```
/vault/userconfig/automation-vault-client $ ls -la ..data/
total 12
drwxr-sr-x    2 root     vault          100 Dec  4 18:01 .
drwxrwsrwt    3 root     vault          140 Dec  4 18:01 ..
-rw-r--r--    1 root     vault         1200 Dec  4 18:01 ca.crt
-rw-r--r--    1 root     vault         1143 Dec  4 18:01 tls.crt
-rw-r--r--    1 root     vault         1675 Dec  4 18:01 tls.key
```

Relevant Helm chart code setting `fsGroup`: https://github.com/hashicorp/vault-helm/blob/1c9c64c8f834fe0771713bc9a52038909a5a5e51/templates/server-statefulset.yaml#L45

Mode bits greater than `0600` is not allowed by the library Vault uses to connect to PostgreSQL:

- Issue: https://github.com/lib/pq/issues/825
- Code: https://github.com/lib/pq/blob/90697d60dd844d5ef6ff15135d0203f65d2f53b8/ssl_permissions.go#L17

**Comment by jasonodonnell** [comment]
Hi @theonewolf,

Yeah, this is the perfect storm of a bunch of limitations.  Lib/PQ has the built in limitation of not allowing the user to override the permissions check on the certificates, Kubernetes `defaultMode` for secrets is manipulated by `fsGroup` and Vault helm doesn't allow you to disable `fsGroup` or set `defaultMode`.

A quick test on my end showed if I copied and chowned the files to say, `/tmp/.pgssl`, the permissions looked correct.  This suggests the template could be altered to have these commands at startup: https://github.com/hashicorp/vault-helm/blob/master/templates/_helpers.tpl#L117-L124

I need to think if there's a way to do this with fsGroup that isn't hacky like editing the entry point.

**Comment by magicalbanana** [comment]
Did you guys find a solution to this? I'm in the same boat. :boat:

**Comment by jasonodonnell** [comment]
I need to test this but I think if we added values to disable `fsGroup` and added support for setting the `defaultMode` on mounted secrets, that should solve this?

**Comment by magicalbanana** [comment]
@jasonodonnell actually, I ended up making the `args` configurable. I kept the `fsGroup`, etc and just extended the script to do what you mentioned above regarding:

> A quick test on my end showed if I copied and chowned the files to say, /tmp/.pgssl ...

and worked for me.

**Comment by Keramblock** [comment]
Seems that we waiting for https://github.com/hashicorp/vault/issues/10925 to be fixed as a prpoper solution for that. btw @magicalbanana solutiob not working anymore because server args are not parametrised anymore.
