### ISSUE TITLE
Proper way of setting up ha.config listener if using LoadBalancer behind Vault

### ISSUE THREAD

**Issue by Aracki** [hashicorp/vault-helm#134]
I'm calling my Vault (3 replicas) via Ingress which points to Service which acts like a LoadBalancer in this case.

Right now my ha.config looks like this:
```
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
```

In [official Vault concepts HA page](https://www.vaultproject.io/docs/concepts/ha.html#behind-load-balancers) it is confusing because it's proposed to use LoadBalancer address and not the actual POD_IP like in my case.

It is working like this, but should I change this according to the official docs?

**Comment by jasonodonnell** [comment]
This doesn't need to be changed, I think.  Vault is using Consul for it's service discovery behind the scenes, this means they know how to communicate/forward correctly.

**Comment by Aracki** [comment]
Thanks for this.
