### ISSUE TITLE
raft support is missing in v0.2.1

### ISSUE THREAD

**Issue by shankarkc** [hashicorp/vault-helm#135]
Hi  vault-helm raft branch has changes raft support. We have been pointed to refer to https://github.com/hashicorp/vault-helm/tree/raft as a working example. But v0.2.1 doesnt contain raft tests. It looks like we dont have raft support in this version. raft branch missing some important features like gateway support.   Is there any plan to merge raft changes to master branch OR update raft branch with latest changes? Do we have a roadmap to support raft at enterprise level? I am employee of `SAP-Ariba` and we have enterprise vault licence. I want to know if we can leverage on raft as vault backend.

**Comment by jasonodonnell** [comment]
Hi @shankarkc,

Raft is not yet supported in Vault Helm.  The raft branch is where the work is currently being stored, however, a feature was required in Vault to support raft in Vault Helm so the progress stopped.  You can view the [CHANGELOG](https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md) for all the released, supported features.  An important note about Raft is that its currently a beta storage backend and it should _not_ be used for anything other than testing.

Additionally, Vault Enterprise is not currently supported by Vault Helm.
