### ISSUE TITLE
Statefulset Liveness Probe failing on standby nodes due to SSL, initial delay and 429 response

### ISSUE THREAD

**Issue by dclark** [hashicorp/vault-helm#137]
- Liveness probe failing when tls is enabled
 - Liveness and readiness probe on standby's receiving a 429 response rather than a 200
 - Liveness probe initialDelaySeconds is set to 5 seconds, value should be configurable and set to a higher default to allow for vault unsealing.

**Comment by jasonodonnell** [comment]
Merged, closing.
