### ISSUE TITLE
"pod has unbound immediate PersistentVolumeClaims" error when installing

### ISSUE THREAD

**Issue by ryanpei** [hashicorp/vault-helm#139]
Versions:
vault-helm 0.2.1
helm 3.0.1
kubernetes 1.15.4

The helm install shows success message, but when I attempt to then initialize/unseal the Vault pods, per https://www.vaultproject.io/docs/platform/k8s/run.html, kubectl returns:
`Error from server (BadRequest): pod vault-0 does not have a host assigned`

This pod is stuck in Pending status. When you kubectl describe the pod, you see the `pod has unbound immediate PersistentVolumeClaims` error.

**Comment by jasonodonnell** [comment]
Hi @ryanpei,

This sounds like the pod is having trouble being scheduled a host. Can you provide the output of `kubectl describe pod vault-0`?

There’s a setting in values, `server.affinity`, which describes the criteria for scheduling. You may try overriding that with nothing to see if affinity is to blame:
`helm install --name vault --set="server.affinity=" .`

**Comment by ryanpei** [comment]
thanks @jasonodonnell , it does look like my PVCs are not able to find any PVs, and I don't have access on this cluster to create my own PVs, so I need to follow up on that. Since that's probably the issue, I'll close this issue. thanks again!

**Comment by itsecforu** [comment]
did u solve it?
