### ISSUE TITLE
Add to Helm Hub

### ISSUE THREAD

**Issue by scottrigby** [hashicorp/vault-helm#14]
Hello 👋 

I saw the [announcement](https://www.hashicorp.com/blog/announcing-the-vault-helm-chart) - exciting 🙌 

Would you like to add this chart to the official https://hub.helm.sh?
See https://github.com/helm/hub and https://github.com/helm/hub/blob/master/Repositories.md

I'm happy to help with anything related - setting up a [Helm repo](https://github.com/helm/chart-releaser), [charts testing](https://github.com/helm/chart-testing), etc - if that sounds useful or fun let us know 😄

**Comment by malnick** [comment]
Thanks @scottrigby! This is a great suggestion. I'm going to bring it up with the team. We really appreciate you reaching out with these great resources!

**Comment by StupidScience** [comment]
Hi, @malnick 
Any news here?

**Comment by mayppong** [comment]
I also would like to see this listed on Helm hub. I believe it can be hosted through GitHub Pages as well.

**Comment by ivanov-aleksander** [comment]
I also waiting for this chart on Helm hub. It is funny situation I couldn't install valt helm chart by terraform. :) Both of them are hashicorp products.

**Comment by mayppong** [comment]
Since the PR#195 for helm 3 support has been merged, it should be good to go on helm hub. Would the maintainer be open to a PR submission for the helm hub? You only either need to enable either the `docs/` folder or `gh-pages` branch name for hosting.

**Comment by karimElmougi** [comment]
We also would like for this chart to get on Helm Hub, or some other repo.

**Comment by carlosjgp** [comment]
It's pretty easy to setup with GitHub actions from Helm
- [helm/chart-testing-action](https://github.com/helm/chart-testing-action)
- [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action)

As mentioned above the only requirements are having a `charts` folder and a branch called `gh-pages`

**Comment by tvoran** [comment]
Hi folks, vault-helm is now listed on Helm Hub: https://hub.helm.sh/charts/hashicorp/vault

More info on using the hashicorp helm chart repo can be found here: https://www.vaultproject.io/docs/platform/k8s/helm#using-the-helm-chart
