### ISSUE TITLE
doc: Return instructions to perform testing

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/vault-helm#155]
I'm not certain why testing instructions were removed in 0.3.0, but I think it could be useful to add to the CONTRIBUTING file if that is a better fit.

https://github.com/hashicorp/vault-helm/commit/7d8ae7df46647a9edc03868d3210f27484d0c9ae#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by jasonodonnell** [comment]
@mbrancato Done!
