### ISSUE TITLE
vault-agent-init with istio

### ISSUE THREAD

**Issue by etiennejournet** [hashicorp/vault-helm#160]
Hi,

I've got problems running vault-agent init containers in a istio mesh. This problem is due to the fact that the istio init container runs before the vault init containers. Related to [this issue](https://discuss.istio.io/t/k8s-istio-sidecar-injection-with-other-init-containers/845).

What does the init container do exactly ? Is it possible to disable it and run secret initialization in podSpec.command ?

Any workaround or input on this is welcome :)

**Comment by etiennejournet** [comment]
[This disables the init container](https://www.vaultproject.io/docs/platform/k8s/injector/index.html#vault-hashicorp-com-agent-pre-populate)

**Comment by jasonodonnell** [comment]
@etiennejournet yes, you'll want to use that annotation.  Closing as this is resolved!
