### ISSUE TITLE
how would one configure this injector with external vault server?

### ISSUE THREAD

**Issue by gokuatkai** [hashicorp/vault-helm#161]
Hi I have a vault server already running outside k8s.
I tried to only deploy all the injector part, but it has TLS connection trouble.
What would I need to do in order to make it work with external vault server please ?

**Comment by gokuatkai** [comment]
I somehow manage to get ride of the error, hard to tell what exactly.

**Comment by vkasgit** [comment]
@gokuatkai I too have an external vault and looking to just deploy the side car injector pods, Did you use this same vault-helm chart to just deploy the side car injector pod? If not, let me know what docker image and documentation you followed. Thanks!

**Comment by gokuatkai** [comment]
@vkasgit hi, I used this chart yes. I have commented out (delete works too :) ) all the server-*.yaml file except the one for the service-account.
Also change the vault address in `injector-deployment.yaml` and that should be it. I used the same image as the chart.

**Comment by vkasgit** [comment]
Awesome, thanks @gokuatkai  One final question. For this whole setup to work does the vault server need to be 1.3.1+ ? I saw somewhere in the readme vault agent needs to be 1.3.1+ but any specific version requirement for the server? My server runs with 1.1.1 so just wanted to check before I start working on this.

**Comment by gokuatkai** [comment]
sorry for late answer, I am not sure to be honest, I started fresh with a brand new 1.3 server.
