### ISSUE TITLE
Dynamic mount_path for vault-agent-init container

### ISSUE THREAD

**Issue by vsantos** [hashicorp/vault-helm#164]
Hello folks, can you help me out with a rookie question?

I'm configuring a centralized vault cluster for N kubernetes clusters as authentication method (custom paths) and I noticed that the `vault-agent-init` container injected by `vault-agent-injector` is not passing the `mount_path` (using no easy external options at least) which fallbacks to the default value `<method type>` (according to the official documentation). The result is a non-existent `/auth/kubernetes/` authentication method:

```
URL: PUT http://vault.vault.svc:8200/v1/auth/kubernetes/login
Code: 400. Errors:

* missing client token" backoff=2.60928227
```

Is there a way to pass a custom `mount_path` using an Environment Variable or flag for the `vault-agent-injector`? I'm not looking to mount an entire `config.json` to solve this "issue" in order to not hardcode the `.template.destination` key, which is dynamic per application.

I could not find any solutions when looking for specific `annotations` or environment variables using the chart.

Example of auto-generated `/tmp/config.json` used by the `vault agent` command:

```
{"auto_auth":{"method":{"type":"kubernetes","config":{"role":"myapp"}},"sink":[{"type":"file","config":{"path":"/home/vault/.token"}}]}}
```

Example of a working `/tmp/config.json` edited directly in the `vault-agent-init` container:

```
{"auto_auth":{"method":{"type":"kubernetes","mount_path":"auth/kubernetes-custom","config":{"role":"myapp"}},"sink":[{"type":"file","config":{"path":"/home/vault/.token"}}]}}
```

**Comment by jasonodonnell** [comment]
Hi @vsantos ,

A PR was created in vault-k8s to add support for this and will be available in the next major release on vault-k8s: https://github.com/hashicorp/vault-k8s/pull/23.

As a workaround for now, you can mount a custom configuration file to change any parameter you wish: https://www.vaultproject.io/docs/platform/k8s/injector/examples.html#configmap-example.

Hope that helps!

**Comment by vsantos** [comment]
Hi @jasonodonnell, thank you very much for your help. (:

I will stick to the PR for now. The usage of a configmap would require a static `.template.destination`

Cheers!
