### ISSUE TITLE
Allow injector to read from remote vault

### ISSUE THREAD

**Issue by damacneil** [hashicorp/vault-helm#167]
The Banzai Cloud banks-vault mutating-webhook helm chart allows secrets to be read from a remote vault instance using kubernetes auth method. I can't see how this can be achieved with the vault agent injector currently and the helm chart doesn't seem to support deploying the agent without the server to read from a remote instance. If this is possible currently, please provide an example to demonstrate the deployment process.

**Comment by tvoran** [comment]
Hey, @damacneil, sorry this was auto-closed without a response. We recently merged #207 which should address your request, and it's been released as part of 0.4.0. Feel free to re-open if you have further questions.
