### ISSUE TITLE
Add support for shareProcessNamespace

### ISSUE THREAD

**Issue by marcusianlevine** [hashicorp/vault-helm#168]
We are using TLS certificates issued via LetsEncrypt, which means we need to periodically reload the Vault servers to pick up the new certificates.

The chart already supports sidecar containers via `server.extraContainers`, but in order to issue the `SIGHUP` signal and trigger a restart, the Pod spec needs `shareProcessNamespace: true` to be available

Ideally this would just be a flag like `server.shareProcessNamespace` with a default value of `false` 

I'm happy to open a PR for this feature if the maintainers are open to the idea

**Comment by jasonodonnell** [comment]
This functionality was added in https://github.com/hashicorp/vault-helm/pull/174.  You can expect this to be in the next release!
