### ISSUE TITLE
Kubernetes Secret?

### ISSUE THREAD

**Issue by esvirskiy** [hashicorp/vault-helm#169]
Is there an example of how this can be used as a Kubernetes Secret vs simply being mounted as a file?

**Comment by jasonodonnell** [comment]
Hi @esvirskiy, are you asking about the injector?  The injector does not support Kube secrets, it only supports file secrets.

**Comment by esvirskiy** [comment]
@jasonodonnell yes. how do I go about creating Kube secrets?

**Comment by jasonodonnell** [comment]
The injector does not support Kube secrets, it only supports file secrets via the sidecar injector.

**Comment by devth** [comment]
Hey @jasonodonnell, I came here looking for this too. Would the capability to create k8s secrets with the injector be considered? I might be able to submit a PR for this.

**Comment by jasonodonnell** [comment]
Hi @devth, 

The injector doesn't talk to Vault, all it does is mutate pod spec to include containers and generates a Vault config.  To create K8s secrets, it would need to impersonate the requestor and then manage Kube secrets.  These are two things we don't really want the injector to be doing as impersonation isn't a great security mode and it greatly expands the scope of the injectors purpose.

That being said we have another project: https://github.com/hashicorp/secrets-store-csi-driver-provider-vault.  This supports syncing secrets to K8s.  Currently this is not production ready but we're hoping to have a GA release by end of this year (we're gearing up to overhaul it as we speak).  Keep a look out for more in this space.

**Comment by devth** [comment]
Thanks @jasonodonnell. I'll keep an eye on `secrets-store-csi-driver-provider-vault`!
