### ISSUE TITLE
Vault config sensitive information

### ISSUE THREAD

**Issue by kg-scality** [hashicorp/vault-helm#175]
Hello,

To my understanding of the chart, vault is loading its config file from a hard coded path that is managed by the chart from a ConfigMap.

From this assessment I failed to understand how I can protect sensitive information that might be needed in vault's configuration. In my case I have an SQL database as a storage backend, meaning I have to store a password in the configuration.

Is my assessment correct ? If it is, I suggest multiple opportunities for improvement in the chart:

- put the entire vault configuration in a kubernetes secret, optionally or not
- enable the editing of vault's command line so that it could be told to launch additional config files
- provide a different way to generate the configuration file

Thanks in advance for your time.

**Comment by jasonodonnell** [comment]
Hi @kg-scality, which database are you using for storage?

**Comment by kg-scality** [comment]
I'm using a MySQL database.

**Comment by jasonodonnell** [comment]
@kg-scality, most database storage drivers allow environment variables to be set for configuration, but it would appear the MySQL doesn't.

On the Vault side we are going to add support for a `MYSQL_PASSWORD` env and on the Vault Helm side we can add `extraArgs` to pass additional config flags to the server command.  Using `extraArgs` in junction with `extraVolumes` that already exists, you would be able to define additional configuration files (stored in a secret) to load with Vault.  Would this help?

**Comment by kg-scality** [comment]
Yes, I definitely think both solutions would help.

**Comment by kg-scality** [comment]
I confirm it works for my setup.
