### ISSUE TITLE
support global imageRegistry setting

### ISSUE THREAD

**Issue by webmutation** [hashicorp/vault-helm#183]
Hello, 

Is there an option to change the imageRegistry to pull from a private registry instead of going to docker.io ? We have a limitation in our PKS cluster where only a private registry is supported.

would it be possible to support the following global setting: 
--set global.imageRegistry=MY_PRIVATE_REGISTRY

**Comment by jasonodonnell** [comment]
Hi @webmutation, that's supported today.  You can simply set the `server.repository` value to do this: https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L68-L77

For example:

```yaml
server:
  image:
    repository: "my-pks-repo/vault"
```

Hope that helps!

**Comment by webmutation** [comment]
Indeed i replaced the 3 locations. Luckly its a simple chart. Thanks. I guess i am just used at that setting from stable charts.
