### ISSUE TITLE
Clearify documentation about Helm 3 / Helm 3 Support. 

### ISSUE THREAD

**Issue by ichtestemalwieder** [hashicorp/vault-helm#184]
Hello, according to https://www.vaultproject.io/docs/platform/k8s/helm/ Helm 3 is not supported? Is this still valid?

This is opposing to the docs in https://github.com/hashicorp/vault-helm, stating "Helm 2.10+ -" that I would interprete as  also supporting Version 3.0. Maybe its better writing the Versions according to the "[semantic versioning selector specification](https://draftin.com/documents/375100?token=rR30GmJJzi4l3BRlD-cHs8lcAcdDAXH4oTzqOWeL0CT0BNv3PZEx0g8pBkI13sQgYXTBqShZ0Ucsqek3Fn3d-aU)".

Should Helm 3 really not be supported it would be kind to support this version. Thanks very much.

**Comment by gnarea** [comment]
I wasn't aware of this, I'm using this chart with Helm 3 and it works OK as far as I can tell. I'm able to unseal, log in and use the kv v2 secrets.

I've only just started using it though and it's only been in development so far, not production.

**Comment by Toady00** [comment]
Some clarification on this would be super appreciated. We just migrated a client off of helm 2 to improve security, and vault is the next step. Having to choose between helm 3 or vault is a decision I'd rather not make.

**Comment by tvoran** [comment]
Thanks for the reminder about the docs! We are actively working on full helm 3 support and tests (#195), and we'll be sure to update the docs as well when that is released.

**Comment by webmutation** [comment]
ditto, in docs it says Helm 3 is not supported, in readme it says Helm 3 is the only supported version, can work with helm 2 but not tested. 
We are still on Helm 2 and will probably stay like this for the next 6 months... I have a working version of Vault will there be problems in the future, are there any plans for a Vault operator?

**Comment by lordofthejars** [comment]
I have seen that helm3 is already supported. Any chance to have a 0.4.0 tag with it? Basically I am asking so I can create a tutorial depending not on master but in a concrete tag that I know it works.

Thank you very much.

**Comment by tvoran** [comment]
Hi folks, vault-helm 0.4.0 has now been released, which includes the helm 3 support mentioned above. We've also updated the website docs to match, so hopefully this clears up any confusion about which helm version is currently supported.

**Comment by lordofthejars** [comment]
Thank you very much.
