### ISSUE TITLE
Inject secret value directly into container env var

### ISSUE THREAD

**Issue by ekhaydarov** [hashicorp/vault-helm#186]
As the title suggests I cannot seem to find in the docs the way that vault can mount the values of a secret directly into environment variables. I assumed it would be possible with the official release since [banzaicloud can directly inject into env var](https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/). 

I assume a recommendation would be to map all your secrets into kubernetes secret and then mount that into the container. However, that doesnt seem simple at all. It would be especially difficult if you want to get secrets from different paths.

Is there a method that I am not aware of to mount secrets?

Thanks

**Comment by jasonodonnell** [comment]
We currently don't support setting environment variables with Vault secrets.  You could optionally define a template that looks similar to a `envrc` file, which your app container could source during startup.

**Comment by ebuildy** [comment]
Is there a reason? As per 12factors reco. ``Store config in the environment``. This will make ``vault`` easier to use with Helm charts that support ``extraEnvs`` value.
