### ISSUE TITLE
No root token on auto-unseal

### ISSUE THREAD

**Issue by fbongiovanni29** [hashicorp/vault-helm#192]
Using GCP KMS Auto-unseal I'm unable to find the root token. I was expecting it to be in the logs (below), I don't know where else to look.

```
kubectl logs pod/vault-0 -n vault
==> Vault server configuration:

      GCP KMS Crypto Key: vault-key
        GCP KMS Key Ring: vault-keyring
         GCP KMS Project: bdt-tool-box
          GCP KMS Region: global
               Seal Type: gcpckms
             Api Address: https://10.4.3.18:8200
                     Cgo: disabled
         Cluster Address: https://10.4.3.18:8201
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: gcs (HA available)
                 Version: Vault v1.3.1

==> Vault server started! Log data will stream in below:

2020-01-31T20:24:33.221Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-01-31T20:24:33.715Z [INFO]  core: stored unseal keys supported, attempting fetch
2020-01-31T20:24:34.018Z [INFO]  core.cluster-listener: starting listener: listener_address=[::]:8201
2020-01-31T20:24:34.018Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
2020-01-31T20:24:34.018Z [INFO]  core: entering standby mode
2020-01-31T20:24:34.070Z [INFO]  core: vault is unsealed
2020-01-31T20:24:34.070Z [INFO]  core: unsealed with stored keys: stored_keys_used=1
```

**Comment by jasonodonnell** [comment]
Hi @fbongiovanni29, the root token is supplied when you initialize Vault.  Auto-unseal does not initialize Vault.  When you can `vault operator init`, your root token was found there.

**Comment by fbongiovanni29** [comment]
I realized that helm uninstalling & re-installing doesn't re-install the gcs backend (seems obvious now) that I had setup previously and reuses it. When I cleared the bucket I was able to reinitialize and get a token

Thanks again Jason! Your response helped me realize that

**Comment by turkenh** [comment]
Ok, in the same scenario;
Is there a way to recover root token (or generate a new one) using data in gcs bucket and gcp kms crypto key ?

**Comment by adrafiq** [comment]
Pluse one.

**Comment by ekawas-td** [comment]
@turkenh or @adrafiq did you ever figure that out? I am using vault-operator and it runs init on it's own ... so i can't pull the token but I have it in my bucket.

**Comment by hoboroten** [comment]
> @turkenh or @adrafiq did you ever figure that out? I am using vault-operator and it runs init on it's own ... so i can't pull the token but I have it in my bucket.

https://banzaicloud.com/docs/bank-vaults/unseal-keys/#decrypting-root-token
