### ISSUE TITLE
How to install vault-agent-injector in K8s with standalone single Vault server? 

### ISSUE THREAD

**Issue by wongkafai** [hashicorp/vault-helm#202]
1. I tried to install vault-helm in rancher(docker version) but I got the following error. How can I resolve it?
![1111111](https://user-images.githubusercontent.com/8857387/74631039-e8bf0b00-5196-11ea-929a-ab1d6827536e.PNG)

2. Since my Vault server is a single server out of K8s, how can I install vault-agent-injector only in K8s in this architecture?

Thanks in advance.

**Comment by smurfralf** [comment]
Same question at https://github.com/hashicorp/vault-k8s/issues/15

**Comment by tvoran** [comment]
Hi @wongkafai, this might be resolved by #207 (which should be released soon), though I'm not familiar with rancher so I can't speak to the specific error you're getting. Can you share the values file used in the chart deployment?

**Comment by wongkafai** [comment]
step 1 Add Catalog
![1](https://user-images.githubusercontent.com/8857387/75145392-d3685480-5733-11ea-9708-f4d8d4d26d45.PNG)
![2](https://user-images.githubusercontent.com/8857387/75145416-de22e980-5733-11ea-9d50-0786fe9c1810.PNG)
![3](https://user-images.githubusercontent.com/8857387/75145424-e2e79d80-5733-11ea-8d8d-781640c44fab.PNG)

step 2 Deployment Catalog 
![4](https://user-images.githubusercontent.com/8857387/75145434-e7ac5180-5733-11ea-91d2-fcfb18b58c5b.PNG)
![5](https://user-images.githubusercontent.com/8857387/75145603-3bb73600-5734-11ea-9b41-e321e91b4f44.PNG)
