### ISSUE TITLE
vault-helm template setting of AGENT_INJECT_VAULT_ADDR not correct

### ISSUE THREAD

**Issue by smurfralf** [hashicorp/vault-helm#208]
The helm template does not allow an external setting of the vault address. Frequent source of questions:
https://github.com/hashicorp/vault-k8s/issues/15
https://github.com/hashicorp/vault-helm/issues/202

The current definition 

     - name: AGENT_INJECT_VAULT_ADDR
        value: {{ include "vault.scheme" . }}://{{ template "vault.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.service.port }}

should be replaced with a template in _helpers.tpl, something like

     - name: AGENT_INJECT_VAULT_ADDR
        value: {{ template "injector.vault_addr" . }}

and helpers containing

    {{- define "injector.vault_addr" -}}
    {{- if .Values.injector.vault_addr -}}
    {{- .Values.injector.vault_addr -}}
    {{- else -}}
    {{- include "vault.scheme" . }}://{{ template "vault.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.server.service.port -}}
    {{- end -}}
    {{- end -}}

**Comment by tvoran** [comment]
Hi @smurfralf, this should now be resolved by #207, thanks.

**Comment by smurfralf** [comment]
Thanks. I'll test it now.
