### ISSUE TITLE
Consistency issues with s3 storage backend

### ISSUE THREAD

**Issue by acesir** [hashicorp/vault-helm#22]
I have seen some very inconsistent issues with s3 storage backend running vault in ha (3 replicas)

the config is generated inside terraform like so and applied via helm_release

```ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "s3" {
        access_key = "${var.aws_access_key_id}"
        secret_key = "${var.aws_secret_access_key}"
        bucket = "${aws_s3_bucket.vault_bucket.id}"
        region = "${var.aws_default_region}"
      }
      seal "awskms" {
        kms_key_id = "${aws_kms_key.vault-kms-key.key_id}"
      }
```

Everything in kubernetes provisions, vault will initialize correctly and seems to be running fine. The auto-unseal via awskms key is also functioning ok. However after creating some test secrets through the UI and enabling different auth methods the UI will randomly not display any of the new secrets and show errors **Unable to find secret at  /path/path** and will even not display the enabled auth methods. This can be said for any other resource created other than the default ones.

Re-logging and refreshing seems to randomly make any of the new resources appear. My question is then is this a potential bug with ha and s3 or is s3 not really a recommended backend for vault ha storage.

Also, none of these issues happen running in standalone with a PVC.

**Comment by ncabatoff** [comment]
Hi @acesir,

As noted in the [S3 docs](https://www.vaultproject.io/docs/configuration/storage/s3.html), it does not support high availability:

```
No High Availability – the S3 storage backend does not support high availability.

Community Supported – the S3 storage backend is supported by the community. While it has undergone review by HashiCorp employees, they may not be as knowledgeable about the technology. If you encounter problems with them, you may be referred to the original author.
```

You'll need to either eliminate your standby servers/replicas, or use a different storage backend.
