### ISSUE TITLE
Wrong number of args for toString Vault-Helm into AKS

### ISSUE THREAD

**Issue by onlykloud** [hashicorp/vault-helm#222]
I'm getting a error when trying to deploy vault-helm into AKS, I follow the next tutorial:

https://github.com/hashicorp/vault-helm

```
$ helm install ./vault-helm
Error: render error in "vault/templates/server-service.yaml": template: vault/templates/server-service.yaml:37:86: executing "vault/templates/server-service.yaml" at <toString>: wrong number of args for toString: want 1 got 0
```
I'm using Helm 2.9.1 and Kubernetes 1.15.7

**Comment by tvoran** [comment]
Interesting, this looks like a similar error to #202 with rancher.

Are you using the latest release of the chart (0.4.0)? It also requires helm 3, so I'd suggest starting there.

**Comment by onlykloud** [comment]
Thanks for your answer, Yes I'm using the last version of the chart, but Helm 2.9.1. I think that's the problem, because I try in another cluster with helm 3 and working fine.
