### ISSUE TITLE
Add support to specify tolerations for the injector

### ISSUE THREAD

**Issue by thecodejunkie** [hashicorp/vault-helm#230]
Hi

I was looking at the `values.yaml` file and I could not find a way to specify `tolerations` for the injector, only for the server? Is this something that could be added to the chart, please?

In general shouldn't the `injector` support the same set of properties (annotations, nodeSelectors, tolerations, etc) as the `server`?

**Comment by tvoran** [comment]
Hi @thecodejunkie, I believe this issue was addressed in #234, and included in v0.5.0: https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#050-april-9th-2020
