### ISSUE TITLE
nodeSelector support for injector

### ISSUE THREAD

**Issue by woowil** [hashicorp/vault-helm#231]
templates\injector-deployment.yaml is missing support for nodeSelector and cystom "helm patch" updates fail. We have a mixed environment with Windows and Linux nodes. The vault and injection pods are automatically created on the windows nodes. I have therefore updated "kubernetes.io/os: linux" under nodeSelector in values.yaml file for the vault pods but unable to do so for vault-injector.

Could you solve this, please.

**Comment by tvoran** [comment]
Hi @woowil, nodeSelector support for the injector was adding in #234, and included in v0.5.0: https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#050-april-9th-2020
