### ISSUE TITLE
Doc: about production ready example

### ISSUE THREAD

**Issue by sereinity** [hashicorp/vault-helm#235]
There is a [list of recommendation](https://www.vaultproject.io/docs/platform/k8s/helm/run/#production-deployment-checklist) that user should respect to be production ready.

It would really help users to put an example or document how to respect those guidelines.

For each points that can't be respected should be documented too and an issue should exists.

By example, maybe some scenario aren't easy to do, like : an E2E encryption + ingress + HA + an external user that connect to vault (with a certificate recognized by its browser, or terraform, or …).

**Comment by jasonodonnell** [comment]
This has been added here: https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes
