### ISSUE TITLE
Running operator init on first run

### ISSUE THREAD

**Issue by christopherbloghett-disney** [hashicorp/vault-helm#25]
Running into an issue with the pods not being alive to run init on the dynamoDB backend. Looks like settings are correct, but getting errors about being sealed. 

How am I able to add an init if db is not setup yet?

`
2019-08-20T17:35:31.970Z [INFO]  core: stored unseal keys supported, attempting fetch
2019-08-20T17:35:32.047Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2019-08-20T17:35:36.425Z [INFO]  core: autoseal: seal configuration missing, but cannot check old path as core is sealed: seal_type=recovery
2019-08-20T17:35:37.048Z [INFO]  core: stored unseal keys supported, attempting fetch
`

**Comment by Skaronator** [comment]
Thats correct IIRC. You need to do initialize the Vault Server first, after that it'll write in the DynamoDB. You can either do that via CLI `vault operator init` or via the Webinterface.

Your DynamoDB should look like this:
```
resource "aws_dynamodb_table" "vault" {
  name           = "vault-storage"
  billing_mode   = "PROVISIONED"
  read_capacity  = 10
  write_capacity = 10
  hash_key       = "Path"
  range_key      = "Key"

  point_in_time_recovery {
    enabled = true
  }

  attribute {
    name = "Path"
    type = "S"
  }

  attribute {
    name = "Key"
    type = "S"
  }
}
```

Provisioned should be cheaper than on demand.

**Comment by christopherbloghett-disney** [comment]
I have ran the command through helm like the previous person that committed the error. It'd just be nice not to have to go that route. I'm deploying with Gitlab CI through Rancher to get the 100% experience of automation. Had to add an ingress template and a secrets template to load a cert in so I can connect. 

Really feeling like this chart shouldn't be public yet. Our prod environment is still running on the incubator scripts over in the Helm charts. 

My personal thoughts about the ideal solution for these charts would be a person/team should be able to define HA Mode, a Backend, a Cert, Auth method. Then a functioning cluster gets provisioned. Sadly that is not the case.

**Comment by jasonodonnell** [comment]
@christopherbloghett-disney Valid concerns and things we're looking to improve on in the near future based on feedback we've been receiving.

**Comment by laurent-iov42** [comment]
This is an issue indeed.
helm sets the deployment status as `FAILED` on first deploy, as vault is not init, and the Readiness Probe fails

**Comment by lostick** [comment]
This is an issue indeed.
helm sets the deployment status as FAILED on first deploy, as vault is not init, and the Readiness Probe fails

**Comment by mdgreenwald** [comment]
Even after running `vault operator init` I am still seeing failing readiness probes which prevent the service from becoming accessible. This is true despite the pods showing its ```"==> Vault server started! Log data will stream in below:"``` message.

```
Readiness:      exec [/bin/sh -ec vault status -tls-skip-verify] delay=5s timeout=5s period=3s #success=1 #failure=2
```

```
Readiness probe failed: Key                Value
```

**Comment by catsby** [comment]
Hey @mdgreenwald - are you also unsealing Vault?

**Comment by mdgreenwald** [comment]
I had not attempted that yet, no.

**Comment by mdgreenwald** [comment]
Hi @catsby No, I had not attempted that yet.

**Comment by SiM22** [comment]
I unseal the vault on eaach pod and it seems to work
