### ISSUE TITLE
Post install automation

### ISSUE THREAD

**Issue by rohitrsh** [hashicorp/vault-helm#251]
Hi,

We have recently deployed vault on Kubernetes; the requirement was to setup end to end vault using helm and integrate with the LDAP backend.

Current, vault helm does not support any post-installation tasks. I have customised it the chart and added a post-installation script. Which is doing the following tasks for me

* Checking vault is up and running.
* Initialising the vault.
* Unsealing the Vault
* Enabling the LDAP auth backend
* Writing the LDAP config.

All the above values can be enabled/disabled using `values.yaml.`

Let me know if you are planning to have such kind of solution in the chart. Would be happy to submit the PR

Thank You
Rohit Sharma

**Comment by jasonodonnell** [comment]
PR welcome for `postStart` lifecycle additions! 💯

**Comment by rohitrsh** [comment]
Closing this one as have created new PR for poststart configs

**Comment by rg13567** [comment]
@rohitrsh I am looking for same solution where i can perform vault init ,unseal and ldap config as part of vault deployment with helm.
Can you please share how did you achieve it ?

**Comment by bakunowski** [comment]
> @rohitrsh I am looking for same solution where i can perform vault init ,unseal and ldap config as part of vault deployment with helm. Can you please share how did you achieve it ?

You might want to take a look at [this](https://github.com/jasonodonnell/vault-agent-demo/blob/master/configs/bootstrap.sh) bootstrap script, which is being run in the `postStart` lifecycle hook as described in [this](https://github.com/hashicorp/vault-helm/pull/315) PR
