### ISSUE TITLE
should helm uninstall cleanup any created pvcs?

### ISSUE THREAD

**Issue by tony-kerz** [hashicorp/vault-helm#254]
since the helm chart (when configured as such) creates the pvc, i kind of expected a `helm uninstall` to remove the pvc, but i'm seeing the pvc remains after an uninstall, is this by design?

in my experience, like with this [jenkins helm chart](https://github.com/helm/charts/tree/master/stable/jenkins), when i let it create the pvc, it will burn it on uninstall, so i have resorted to creating the pvc separately and [specifying it as an existing pvc](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L502) to retain the pvc if i need to `helm uninstall` for some reason.

i was going to ask if you would consider allowing an option for an existing pvc on your vault chart,
but i'll wait for your response to my original question before i go there :)

cheers, tony.

**Comment by jweissig** [comment]
Could this be done with an additional flag on uninstall? I'm just thinking that with the new raft storage backend users could inadvertently blow away their data store on uninstall. Wanted to make sure this was highlighted when considering the design.

**Comment by jasonodonnell** [comment]
@tony-kerz This is a design decision specifically if Vault is storing data on volumes to avoid unintentional deletes.  Overall we prefer manual clean up of PVCs to err on the side of caution.
