### ISSUE TITLE
Is the latest Helm v2 tested chart version (v0.3.3) compatible with the latest Vault version (v1.4.1)?

### ISSUE THREAD

**Issue by Xtigyro** [hashicorp/vault-helm#294]
Is the latest Helm v2 tested chart version (v0.3.3) compatible with the latest Vault version (v1.4.1)?

It's been tested and appears to be completely fine. It's also not mentioned anywhere explicitly that the newer chart versions expect newer Vault versions or vice versa.

It'll be nice to know that we can still use the latest app versions with Helm v2 - and that to be confirmed explicitly by HashiCorp itself.

**Comment by pcman312** [comment]
Thanks for opening this issue! Are you aware of our forum located here: https://discuss.hashicorp.com/c/vault/30? If possible, we appreciate it when folks ask questions there because we generally use Github for bugs and enhancement requests.

Chart 0.3.3 should be compatible with Vault 1.4.1, however we have not explicitly tested it.

**Comment by Xtigyro** [comment]
Many production environments still use Helm v2 - Vault app's releases should be tested against the last Helm v2 compatible version of the chart.

**Comment by acarsercan** [comment]
Hi,

We are looking to migrate from incubator chart to offical chart, however we are still using helm v2 and unable to see v0.3.3 in the chart repo

```
sercan@sercan-XPS-13-9370:~/ccuk_git/ccuk-prod-flux/charts/vault-helm(master)$ helm search hashicorp/vault --versions
NAME           	CHART VERSION	APP VERSION	DESCRIPTION                               
hashicorp/vault	0.6.0        	1.4.2      	Official HashiCorp Vault Chart            
hashicorp/vault	0.5.0        	           	Install and configure Vault on Kubernetes.
hashicorp/vault	0.4.0        	           	Install and configure Vault on Kubernetes.
```

Is this correct or have I missed something? I'm seen chart not found when doing a manual or flux install

**Comment by tvoran** [comment]
Hi @acarsercan, I believe v0.4.0 was when we first started using our helm chart repository. Older versions would need to be installed from the github repo source: https://github.com/hashicorp/vault-helm/tree/v0.3.3#usage

**Comment by Xtigyro** [comment]
@tvoran So the latest Helm v2 chart for Vault is **NOT** tested against the latest Vault app versions and it's **NOT** hosted as a Helm chart.

Is that really the current state?
