### ISSUE TITLE
Unable to set pod annotations when using dev mode

### ISSUE THREAD

**Issue by yafernandes** [hashicorp/vault-helm#301]
I need to setup pod annotations in my dev environment and by the line below the template is ignoring pod annotations if in dev mode.

https://github.com/hashicorp/vault-helm/blob/ac6089c45ef66d4e1eed0e279364ccbb2f8a6eda/templates/_helpers.tpl#L265

**Comment by KadenLNelson** [comment]
this is a duplicate of https://github.com/hashicorp/vault-helm/issues/241

**Comment by tvoran** [comment]
Fixed in #371
