### ISSUE TITLE
Support placing plugins on the server

### ISSUE THREAD

**Issue by allandegnan** [hashicorp/vault-helm#302]
My understanding is vault needs custom plugins to exist on the filesystem at _some_ path but I can't see an obvious way of achieving this via the current chart.

Two methods I've seen are:

1. Stuff binaries in a configMap. 
2. Support emptyDir for extraVolumes.

I've written a PR for option 2.

**Comment by jasonodonnell** [comment]
@allandegnan Binaries definitely shouldn't go into configMaps.  I'm curious how you will populate the emptyDir with the binary?  Using an init container to fetch it?

**Comment by allandegnan** [comment]
@jasonodonnell - Yep, pretty much.  cp from the initContainer.

Save us from having to build & track your (hashi) containers.

**Comment by jasonodonnell** [comment]
#314 makes this possible now.  Closing.

**Comment by timclifford** [comment]
Is there not a better/new way to load custom plugins into vault other than the above? I'm using the second approach but was wondering if custom plugins were better supported now
