### ISSUE TITLE
Allow disabling server deploy

### ISSUE THREAD

**Issue by jamielennox** [hashicorp/vault-helm#304]
I can enable disable the injector and the UI component easily via values.yaml but for some reason the server can't be enabled/disabled in the same way. 

I can't be the only one who already has vault established externally and am trying to only deploy the injector? Is there a reason why this wouldn't be a supported configuration?

**Comment by krzysztof-miemiec** [comment]
From what I see in the docs and template, it seems to be possible. Try setting [`injector.externalVaultAddr`](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#externalvaultaddr).

**Comment by jamielennox** [comment]
hmm, looking back i'm not sure what i was seeing here as we've definitely been deploying this way. Needing an `externalVaultAddr` makes sense, i guess i was just expecting a `server.enabled` in the same way as the other components. 

Anyway, thanks for chasing up and i'll close this as it's obviously possible.
