### ISSUE TITLE
Setting the default template for the injector

### ISSUE THREAD

**Issue by mitom** [hashicorp/vault-helm#307]
Hi,

We'd like to be able to configure the default template for the injector. For most of our usecases, we just want the injector to output json. Therefore we'd prefer if the default template was
```
{{ with secret "/path/to/secret" }}
{{ .Data.data | toJSON }}
{{ end }}
```

As far as I can tell there is another problem that makes this difficult to achieve, which is to use a template we need to use 2 annotations, with the path to the secret defined in both. I.e.
```
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-secret: "secret/my-secret"
        vault.hashicorp.com/agent-inject-template-secret: |
          {{- with secret "secret/my-secret" -}}
          {{ .Data.data | toJSON }}
          {{- end }}
```
This works, however it'd be very nice to not have to duplicate this for every single secret injected, and being able to configure that unless the `template` is provided it'll output json (or preferably, it's a template the user can provide in the configuration of this chart in some way).

Any suggestions to achieve this? Thank you

**Comment by jasonodonnell** [comment]
This is currently not supported in the Vault K8s Injector, but is definitely useful.  Closing as this is a Vault K8s feature request and already asked for here: https://github.com/hashicorp/vault-k8s/issues/103.
