### ISSUE TITLE
server-ha-active-service does not update after the active pod changes

### ISSUE THREAD

**Issue by danielmittelman** [hashicorp/vault-helm#318]
I'm using the `server-ha-active-service` ClusterIP service to scrape metrics using Prometheus in a HA cluster.

Until now, my cluster has experienced a re-election process multiple times, yet there is nothing that changes the labels on the pods to indicate which one is the active. This is problematic since, according to the documentation,

> The `/v1/sys/metrics` endpoint is only accessible on active nodes and automatically disabled on standby nodes

So far I've had to manually edit the `vault-active` label every time a pod loses its "active" state, which is not optimal

**Comment by jasonodonnell** [comment]
Hi @danielmittelman,

Can you give me more information about your Vault deployment?  Which storage are using?  What version of Vault?

On my end I'm seeing label changes until quorum is lost in the cluster.  Once quorum is restore the active pod comes back.

**Comment by jasonodonnell** [comment]
Also, do you have Kubernetes service registration enabled on your server config? 
https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L404
https://github.com/hashicorp/vault-helm/blob/master/templates/server-statefulset.yaml#L75-L82

**Comment by danielmittelman** [comment]
Hi @jasonodonnell,
I'm using Vault v1.4.2 with the latest version of this chart. **I do not, however, have service registration in my config**, I wasn't aware this existed.

I will update my configuration and will report back if that fixed the issue

**Comment by patrickstump** [comment]
Any update on this?  I am seeing the same thing.
I am trying to use the vault-active service and only the vault-0 pod seems to be selected, due to the other pods not having the "vault-active=true" label.

I am deploying via gitlab and trying to find a way to autoscale and configure pods to auto join the raft cluster. As such, I have used the raft join command pointed at the vault-active service, which seems to work. I am unsure if that could cause this issue though.

This is a dev cluster for me, so I am happy to try suggestions or get more info.

I setup this cluster by:
1. Installing Helm Chart with custom values.yaml to use raft (config below).
2. Init vault on vault-0 and using transit key to autounseal (confirmed this works)
3. Join vault-1 to raft cluster (tried vault-0 and vault-active for this, both seem to work for joining)
4. Confirmed vault-0 and vault-1 auto unseal if they are taken down and brought back up.
5. Joined vault-2 pod to cluster, all showing ready in pod status and log
6. Check vault-active service, only vault-0 shows as endpoint.
7. Even though vault-1 and vault-2 come up and are ready, their label for vault-active is still false.

**Config**:
Vault: Helm Chart v0.6.0
Using Gitlab CICD to deploy.

Values file configured for HA using raft:
```
ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}
        
        seal "transit" {
          address = "https://vault.example.com"
          disable_renewal = "false"
          key_name = "autounseal"
          mount_path = "transit/"
          tls_skip_verify = "true"
        }
```
I reviewed https://www.vaultproject.io/docs/configuration/service-registration/kubernetes
Raft Peers look like they are good:
```
/ $ vault operator raft list-peers
Node                                    Address                        State       Voter
----                                    -------                        -----       -----
50a00725-0937-8860-41a1-f5a99968d33a    vault-0.vault-internal:8201    leader      true
4381827e-ac1c-bb9a-174b-0e8edfe23b32    vault-1.vault-internal:8201    follower    true
b7c500d2-16c4-8d64-ee39-b189f6a2ee88    vault-2.vault-internal:8201    follower    true
 
```



vault-0 has the ip address 10.42.2.100
```
kubectl describe service vault-active -n vault-263-dev
Name:              vault-active
Namespace:         vault-263-dev
Labels:            app.kubernetes.io/instance=vault
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=vault
                   helm.sh/chart=vault-0.6.0
Annotations:       <none>
Selector:          app.kubernetes.io/instance=vault,app.kubernetes.io/name=vault,component=server,vault-active=true
Type:              ClusterIP
IP:                10.43.17.174
Port:              http  8200/TCP
TargetPort:        8200/TCP
Endpoints:         10.42.2.100:8200
Port:              https-internal  8201/TCP
TargetPort:        8201/TCP
Endpoints:         10.42.2.100:8201
Session Affinity:  None
Events:            <none>
```

**Comment by patrickstump** [comment]
Per https://www.vaultproject.io/docs/configuration/service-registration/kubernetes
I do not see a role ``` name: vault-service-account```

```
kubectl get role -n vault-263-dev
NAME                              AGE
vault-discovery-role              3h17m
``` 
However there is a **vault-discovery-role**.  Is that the role that is being used for the update?
```
kubectl describe role vault-discovery-role -n vault-263-dev
Name:         vault-discovery-role
Labels:       app.kubernetes.io/instance=vault
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault
              helm.sh/chart=vault-0.6.0
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  pods       []                 []              [get watch list update patch]
```

**Comment by jasonodonnell** [comment]
> I am trying to use the vault-active service and only the vault-0 pod seems to be selected, due to the other pods not having the "vault-active=true" label.

@patrickstump `vault-active` service points to the current leader in the cluster.  There will only ever be one leader.  The service description above looks correct and the service registration is doing it's job correctly.  If `vault-0` were to lose leadership, it would update the service to point to the pod that wins the election.  @danielmittelman simply did not have the Kubernetes service registration enabled in the Vault config.

You should not use the `vault-active` service to bootstrap your raft cluster.  As per our documentation, the Raft cluster should be using the `vault-internal` service so pods can directly communicate with one another.  IE: `vault operator raft join http://vault-0.vault-internal:8200`.  As the Raft cluster builds, they will all use their unique DNS names to communicate with each other.

As for auto-scaling, we recently added a `server.postStart` feature in Vault Helm.  You could mount a script using `extraVolumes` and have the `postStart` value run it.  This would give you flexibility to do more automation.  Raft currently doesn't have an auto join feature.

One note about postStart, it doesn't fire until the pod is ready.  See my PR for an example of how to configure the health probe to avoid this issue: https://github.com/hashicorp/vault-helm/pull/315

**Comment by patrickstump** [comment]
> @patrickstump `vault-active` service points to the current leader in the cluster. There will only ever be one leader. The service description above looks correct and the service registration is doing it's job correctly. If `vault-0` were to lose leadership, it would update the service to point to the pod that wins the election. @danielmittelman simply did not have the Kubernetes service registration enabled in the Vault config.

@jasonodonnell That all makes alot of sense.
I did see that the ingress is now pointing to vault-active. Does this mean that the ingress is only ever going to use one pod? Reading the previous PR Ihought it would point to vault pods unsealed and ready to be used by the load balancer (round robin etc).  
I can start a separate ticket, unless it is addressed someplace else, but how do I get the ingress to use all the active pods (say i want to scale to 30 pods)?

> 
> You should not use the `vault-active` service to bootstrap your raft cluster. As per our documentation, the Raft cluster should be using the `vault-internal` service so pods can directly communicate with one another. IE: `vault operator raft join http://vault-0.vault-internal:8200`. As the Raft cluster builds, they will all use their unique DNS names to communicate with each other.

Understood, that makes sense.
 
> As for auto-scaling, we recently added a `server.postStart` feature in Vault Helm. 
> One note about postStart, it doesn't fire until the pod is ready. See my PR for an example of how to configure the health probe to avoid this issue: #315
You could mount a script using `extraVolumes` and have the `postStart` value run it. This would give you flexibility to do more automation. Raft currently doesn't have an auto join feature.

Yep, saw that and was planning on using it.

**Comment by patrickstump** [comment]
@jasonodonnell I think i found the answer to my question:
```
Starting a standby Vault node
A standby Vault node is initialized and unsealed, but does not hold the leader election lock. The standby node cannot serve user requests. It forwards user requests to the active node. If the active node goes down, a standby node becomes the active node.
```

I'll move with that for now.  It's a bit weird of a kubernetes setup to me though. I would think with the ability to autoscale it would be good to have the requests spread out among the cluster. 
This gets me moving though.
Thanks
