### ISSUE TITLE
Potential Security flaw

### ISSUE THREAD

**Issue by mrafieee** [hashicorp/vault-helm#322]
This is an enhancement suggestion.
the unseal credentials are exposed in configmaps in K8s clustrer

we are populating auto unseal credentials as configs in configmaps 
`https://github.com/hashicorp/vault-helm/blob/master/templates/server-config-configmap.yaml` 

in the value files it is referred 
```
config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

      # Example configuration for using auto-unseal, using Google Cloud KMS. The
      # GKMS keys must already exist, and the cluster must have a service account
      # that is authorized to access GCP KMS.
      #seal "gcpckms" {
      #   project     = "vault-helm-dev"
      #   region      = "global"
      #   key_ring    = "vault-helm-unseal-kr"
      #   crypto_key  = "vault-helm-unseal-key"  
```
these values should be secured in secrets not configmaps.

**Comment by jasonodonnell** [comment]
Hi @mrafieee, we already have a way of protecting sensitive secrets in configuration files.  See our documentation: https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations.
