### ISSUE TITLE
Upgrading 0.5.0 to 0.6.0 ingress for HA no longer works

### ISSUE THREAD

**Issue by gtrog** [hashicorp/vault-helm#325]
Hi, I just upgraded the helm chart from 0.5.0 to 0.6.0 and noticed a change in the ingress controller that seems to cause the ingress controller from working properly: https://github.com/hashicorp/vault-helm/pull/270/files#diff-2e7c579e3505049abe578241a8c4e7adR6

Essentially, what I'm seeing is the active vault pod in the HA set up never receives the label `vault-active` even though it's showing as `Running 1/1` and I can verify that curling the regular `vault` service works fine, but, because the ingress controller now is pointing at the `vault-active` service and no pods ever receive this label, it can't route the request.

I'm curious if I misconfigured something and how these pods normally receive this label?

**Comment by tvoran** [comment]
Hi @gtrog, if you're running with `server.ha.enabled=true`, you'll need to have `service_registration: kubernetes {}` present in `server.ha.config` or `server.ha.raft.config`. That is how the pods get labeled.

**Comment by gtrog** [comment]
That did the trick, thank you very much!

**Comment by tvoran** [comment]
Glad to hear it! We need to document that requirement better somewhere, thanks for bringing it up.
