### ISSUE TITLE
Setting up consul secret engine?

### ISSUE THREAD

**Issue by Skaronator** [hashicorp/vault-helm#33]
I'm trying to setup the [Consul Secrets Engine](https://www.vaultproject.io/docs/secrets/consul/index.html) but it seems to be impossible with the current Helm Charts.

I also use the Hashicorp Consul Helm Charts which creates a Consul Agent on each node of my kubernetes cluster (DaemonSet). (Described [here](https://www.consul.io/docs/platform/k8s/run.html#client-agents)) Which is fine and sounds logical. The Consul Docs also shows how I would be able to access the Consul Agent (Described [here](https://www.consul.io/docs/platform/k8s/run.html#accessing-the-consul-http-api)) which makes the Node IP available as environment variable.

The issue is that I need a address to the Consul Agent when configuring the Secrets Engine in Vault. And the Value cannot be a Environment Variable _and_ the same value must be reachable from each Vault Pod.

```bash
vault write consul/config/access \
    address=127.0.0.1:8500 \
    token=xxxx-xxxx-xxxx-xxxx-xxxx
```

The only solution I can think of is adding a Consul Agent in the Pod and then use the localhost IP to resolve to that agent. Is there a better method or is that the only one?

**Comment by Skaronator** [comment]
Maybe creating a loopback interface before the container starts which will map the Node IP to 127.0.0.2 or something like that could work as well?

**Comment by jasonodonnell** [comment]
Hi @Skaronator!

I think Consul's service should be reachable from the Vault pods:

```bash
[~] kubectl get services | grep consul
consul-consul-dns      ClusterIP   10.102.183.216   <none>        53/TCP,53/UDP                                                             7m30s
consul-consul-server   ClusterIP   None             <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   7m30s
consul-consul-ui       ClusterIP   10.100.48.130    <none>        80/TCP

[~] kubectl exec -ti vault-0 -- ping consul-consul-server
PING consul-consul-server (10.32.0.6): 56 data bytes
64 bytes from 10.32.0.6: seq=0 ttl=64 time=0.064 ms
64 bytes from 10.32.0.6: seq=1 ttl=64 time=0.061 ms
64 bytes from 10.32.0.6: seq=2 ttl=64 time=0.061 ms
```

Thoughts?

**Comment by jasonodonnell** [comment]
After speaking with Consul folks, it might be better to create a service that load balances the agent nodes for this particular use case:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: consul-agent-service
spec:
  selector:
    app: consul # This might be different for you
    component: client
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
```

Then configure Vault to use it:

```bash
vault write consul/config/access \
    address=consul-agent-service:8500 \
    token=xxxx-xxxx-xxxx-xxxx-xxxx
```

**Comment by Skaronator** [comment]
Shouldn't Vault talk to the consul agents instead of talking with the server directly?

**Comment by Skaronator** [comment]
Just saw the other email... Wouldn't it be better for Vault to talk with the agent on the same node? Instead of load balancing to a different instance?

**Comment by jasonodonnell** [comment]
@Skaronator Agreed that is ideal and what we would like, however, it would require some sort of loop back like you are suggesting.  Without a loop back something like node IP could be used but that has limitations: node ip is persisted in Vault config and if the node goes down it's no longer accessible.  By using an agent service, we can ensure an agent always responds.

Going to think more on this but these are my initial thoughts.

**Comment by Skaronator** [comment]
Thanks for your input, I think this is enough for now.

**Comment by chancez** [comment]
I managed to get vault to connect to consul as deployed via the `consul-helm` chart by adding a service accessing the consul client agent, but then there's TLS issues. 

```
/ $ vault write consul/config/access address=consul-client.consul:8501 scheme=https token=$VAULT_CONSUL_TOKEN
Success! Data written to: consul/config/access
/ $ vault read consul/creds/my-role
Error reading consul/creds/my-role: Error making API request.

URL: GET http://127.0.0.1:8200/v1/consul/creds/my-role
Code: 400. Errors:

* Put https://consul-client.consul:8501/v1/acl/token: x509: certificate is valid for localhost, not consul-client.consul
```

**Comment by chancez** [comment]
Well, setting `global.tls.httpsOnly` let me access it over 8500 at least. I can work on how to share the client CA to vault, but overall I'd love a prescribed/automated way to do all this.
