### ISSUE TITLE
Unable to connect to Vault Pods using SVC.

### ISSUE THREAD

**Issue by rdeb22** [hashicorp/vault-helm#342]
Hi Team. 
Requirement.
1. My end goal is to connect to LEADER POD and not the active pods. 

2. Currently,
I am using the service `vault` which works but it follows a round-robin fashion all pods including nonleader pods. 

3. I see there is a separate service named `vault-active` which not seem to connect and gives `503 Service Temporarily Unavailable`

4. On checking, I see SVC `vault-active`  requires service_registration, I also enabled but did not have luck. 
vaultproject.io/docs/configuration/service-registration/kubernetes

Can someone help me to meet my requirement by checking my config for service_registration or changing service `vault` so that it connects to only leader pod? 

```
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault/"
        address = "consul-service.spr-apps.svc.cluster.local:8500"
        max_parallel = "1000"
      }

      service_registration "kubernetes" {
        namespace      = VAULT_K8S_NAMESPACE
        pod_name       = VAULT_K8S_POD_NAME
      }
```

**Comment by tvoran** [comment]
Have you tried an empty service registration block? 

```hcl
      service_registration "kubernetes" {}
```

I think the VAULT_K8S_NAMESPACE and VAULT_K8S_POD_NAME environment variables should already be set on the vault pods, and the service_registration will pick those up.

**Comment by rdeb22** [comment]
@tvoran  Thanks for your reply. 
Yes I have tested using empty service registration block and SVC does not work at all.

**Comment by tvoran** [comment]
Ok, here are some other things to double check:

- Is this with vault 1.4.0 or greater? service_registration for kubernetes was added in 1.4.
- Do the vault logs show any errors? If vault is having trouble connecting to consul, service_registration will not label the pods.
- Is HA Enabled showing as true in `vault status`? Example running `vault status` on vault-0 of the statefulset:

```console
$ kubectl exec -ti vault-0 -- vault status
Key                Value
---                -----
Seal Type          shamir
Initialized        false
Sealed             true
Total Shares       0
Threshold          0
Unseal Progress    0/0
Unseal Nonce       n/a
Version            n/a
HA Enabled         true
```

- Are the pods being labeled by the service registration at all? Even before vault is initialized or unsealed, the labels should appear on the pods. Specifically, "vault-active" is the label the `vault-active` service looks for. Example:

```console
$ kubectl get pod vault-0 -o json | jq .metadata.labels
{
  "app.kubernetes.io/instance": "vault",
  "app.kubernetes.io/name": "vault",
  "component": "server",
  "controller-revision-hash": "vault-6dccbbb8bd",
  "helm.sh/chart": "vault-0.6.0",
  "statefulset.kubernetes.io/pod-name": "vault-0",
  "vault-active": "false",
  "vault-initialized": "false",
  "vault-perf-standby": "false",
  "vault-sealed": "true",
  "vault-version": "1.4.2"
}
```

- Is vault initialized and unsealed? No pods will be labeled with `vault-active: true` until both occur.

**Comment by rdeb22** [comment]
Hello Theron

Thank you for your reply.
I see the variables are not set in my case. Please see below. Please guide
how can I set them up for the pods. Also, my version is 1.3.2


   - Is this with vault 1.4.0 or greater? service_registration for
   Kubernetes was added in 1.4.
   / $ vault -v
   Vault v1.3.2
   I am on 1.3.2, how can I achieve connections to only Leader and not
   other pods.

   - Do the vault logs show any errors? If the vault is having trouble
   connecting to the consul, service_registration will not label the pods
   NO errors on logs.

   - Is HA Enabled showing as true in vault status? Example running vault
   status on vault-0 of the statefulset:
   Yes shown below.


```
kubectl exec -ti vault-0 -- vault status

Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.3.2
Cluster Name           vault-cluster-88981dd1
Cluster ID             02643eda-46c8-f8b5-c337-96747bc7a736
HA Enabled             true
HA Cluster             https://vault-1.vault-internal:8201
HA Mode                standby
Active Node Address    http://10.244.16.25:8200
```

```
kubectl  get pod vault-0 -o json | jq .metadata.labels

{
  "app.kubernetes.io/instance": "vault",
  "app.kubernetes.io/name": "vault",
  "component": "server",
  "controller-revision-hash": "vault-58f5c84f8f",
  "helm.sh/chart": "vault-0.5.0",
  "statefulset.kubernetes.io/pod-name": "vault-0"
}

```
I have only these variables.

**Comment by tvoran** [comment]
The only way to have the vault server pods labeled according to their active status is to upgrade to vault 1.4 so that service registration is supported.

If upgrading vault isn't an option, an alternative setup would be to set a custom readiness check for the pods that marks only the active pod as ready, and then add another service manually that would only connect to ready pods. Something like this:

chart values:
```yaml
server:
  readinessProbe:
    enabled: true
    path: /v1/sys/health
```

custom service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-example-active
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  type: ClusterIP
```

Then connections to the `vault-example-active` service would be routed only to the active vault pod. 

This setup does make it hard to judge the status of the vault pods at a glance since the standby's will always be marked as not ready, regardless of their sealed status.
