### ISSUE TITLE
Add Volume and Volume Mount to StatefulSet

### ISSUE THREAD

**Issue by enhendrickson** [hashicorp/vault-helm#349]
I have reviewed the YAML for StatefulSet and feel as though I must be missing it somehow, but I would like to be able to add a custom Volume and Volume Mount to the StatefulSet container, but the values-to-manifest mapping that occurs in the chart doesn't seem to allow it.  

Can someone either point out what I'm missing or confirm this for me?  This doesn't seem likely so I am not trusting my eyes.  I understand that you can map secrets and config maps, but why can't I add (or if I can, then how) a custom Volume and Volume Mount.  

For interest, I'm doing this because I want to mount an AWS EFS share to be used as an Audit Device and this requires a pre-deployed Persistent Volume.  Dynamic provisioning is not supported.  Please assist or confirm that this is the case.

**Comment by tvoran** [comment]
Hi @enhendrickson, good question, and it looks like https://github.com/hashicorp/vault-helm/pull/314 will be adding this.

**Comment by enhendrickson** [comment]
@tvoran @jasonodonnell any idea when #314 will be merged?

**Comment by ngarafol** [comment]
@enhendrickson some PRs take months to merge, if ever. Could be better off branching and including PR yourself (it you want to get your feet wet :) )

**Comment by enhendrickson** [comment]
@ngarafol already did that (sans the PR since it already exists)... very familiar with this process.  It just seems that PR #314 was close and could be merged any day. So I wanted to bump the owners.

**Comment by jasonodonnell** [comment]
#314 was merged and will be in the next release.
