### ISSUE TITLE
Vault HA without auto unsealing

### ISSUE THREAD

**Issue by victorterraga** [hashicorp/vault-helm#350]
I have deployed a Vault with HA inside my cluster and unsealed it manually. When accessing it from another pod in my cluster i use the address of the vault load balancer **http://vault.default.svc.cluster.local:8200**, so it internally redirects to the active Vault i understand.

Testing HA i killed two of the three Vaults, so as i do not use auto unsealing these two Vaults will restart but won't be available. What i was expecting is the Vault load balancer to redirect my request to the only unsealed and active Vault, but that's not happening, it redirects to any of the three Vaults but the requests in two of them fail as they are not unsealed.

I saw the deployed services:
![image](https://user-images.githubusercontent.com/40562322/86351509-a5a49680-bc64-11ea-9844-c32e2b0c7e3b.png)
And i thought i could make all my request to directly access the vault-active node not the vault one, (http://vault-active.default.svc.cluster.local:8200), but it seems that i cannot reach it.

Is there any approach you would recommend me for deploying Vault HA without auto unsealing mechanism (as aws kms)? I just need to deploy Vault with HA, and if any Vault crashes I would expect the load balancer to use just the other 2 Vaults, or a way to directly access the Active one.

P.S. I use Helm and the last Vault release

**Comment by tvoran** [comment]
The recommended approach is to use vault 1.4, and add `service_registration` for kubernetes to your config, which is the default in the chart config: https://github.com/hashicorp/vault-helm/blob/93f5190a60065a6a13c7a84b1cf546de7f99bc59/values.yaml#L441. Then the `vault-active` service will only route to the active vault pod. Use `kubectl get endpoints` to see the pods in each service.

The other vault services are configured to contain all the vault pods, regardless of ready or active status.

**Comment by victorterraga** [comment]
I have added the part of the `service_registration` to my `values.yaml` but when i execute the `kubectl get endpoints` command the output shows all the endpoints of my Vault nodes but the `vault-active` one is still <none>

![image](https://user-images.githubusercontent.com/40562322/86466135-66914680-bd33-11ea-9ee6-dd4a5696f125.png)

The problem is that internally i do not know how to reference the active Vault, (as i cannot direclty target the vault-active endpoint). And in the use case that i explained in the issue i cannot let the internal Vault load balancer to redirect to any Vault, as it may redirect to an unsealed Vault.

Thanks for the response.
