### ISSUE TITLE
Var declaration syntax error in the server-route and server-ingress

### ISSUE THREAD

**Issue by gkarthiks** [hashicorp/vault-helm#356]
**Describe the bug**
The templates for the server-route and server-ingress has the variable serviceName declaration in the lines 6 and 7 correspondingly. They are just equated with "=" sign rather than ":=".

**To Reproduce**
1. Do a helm install command on the vault chart
2. Below error would appear
```Error: parse error in "vault/templates/server-ingress.yaml": template: vault/templates/server-ingress.yaml:7: unexpected "=" in operand```
3. After fixing this same error will appear for the server-route

**Expected behavior**
There should be any syntax errors and the ingress or route should deploy without issue accordingly

**Environment**
* Kubernetes version: 1.11
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): OpenShift
  * Other configuration options or runtime services (istio, etc.): -n/a-
* vault-helm version: 0.6.0

Chart values:

Same default values

**Additional context**
-n/a-

**Comment by jasonodonnell** [comment]
Closing due to Helm version error.
