### ISSUE TITLE
Add to hub.helm.sh

### ISSUE THREAD

**Issue by woodcockjosh** [hashicorp/vault-helm#359]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I can find this chart on hub.helm.sh

**Describe alternatives you've considered**
Google it and land on this github repo

**Additional context**
Example: https://hub.helm.sh/charts/hashicorp/consul

**Comment by tvoran** [comment]
Hi there, this chart is available on helm hub at https://hub.helm.sh/charts/hashicorp/vault

It seems to show up in the search results for me there too, and you can view all the hashicorp charts here: https://hub.helm.sh/charts/hashicorp
