### ISSUE TITLE
remove needs to run as privileged 

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault-helm#36]
it looks like vault needs to run as a privileged pod because of the additional MLOCK capability.
A few considerations:
1. it's always a difficult conversation to have a pod running as privileged, so this static setting will slow down adoption
2. if MLOCK is what is needed then you don't need a fully privileged pod, you could create a podSecurityPolicy (https://kubernetes.io/docs/concepts/policy/pod-security-policy/) to allow only as an additional capability MLOCK.
3. My opinion is that MLOCK is not even needed. In fact it is a best practice to run Kubernetes with swap disabled and most Kubernetes distributions have adopted this approach. So, if the only function of MLOCK is to prevent memory from being swapped to disk, it's not needed in most cases and there should be a chart flag to select an installation option in which MLOCK is disabled.

**Comment by jasonodonnell** [comment]
This has been merged, closing!
