### ISSUE TITLE
No pods can be created after installing helm chart on private GKE cluster

### ISSUE THREAD

**Issue by bazhip** [hashicorp/vault-helm#366]
**Describe the bug**
I've installed the helm chart to my private GKE cluster and pointed it at an external vault address. After this, any newly created pod will not schedule across the entire cluster.

**To Reproduce**
`helm install vault hashicorp/vault --set "injector.externalVaultAddr=https://vault.myserver.com:8200"`
`kubectl apply -f anythingelse.yaml`

Now no pods from whatever I applied will appear. When I describe the replicaset, the errors I get for any new pods are:

`Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  8m52s               replicaset-controller  Error creating: context deadline exceeded
  Warning  FailedCreate  27s (x16 over 11m)  replicaset-controller  Error creating: Timeout: request did not complete within requested timeout
`
once I `helm uninstall vault` the previously failed deployments all immediately appear.

**Expected behavior**
I should be able to install anything else to my cluster after installing this helm chart.

**Environment**
* Kubernetes version: 1.16
  * GKE Private Cluster
* vault-helm version: 3

**Comment by tvoran** [comment]
Hi @bazhip, are your worker nodes able to connect to port 8080 on your master nodes? That's a common cause for this sort of behavior: https://www.vaultproject.io/docs/platform/k8s/injector/examples#before-using-the-vault-agent-injector

Some other things to keep in mind connectivity-wise:
- pods inside your k8s cluster need to be able to connect to vault
- vault needs to be able to connect to your cluster's k8s API

**Comment by bazhip** [comment]
Hey @tvoran , it looks like I missed that part since it says at the heading "Before applying Vault Agent injection annotations to pods, the following requirements should be satisfied:" and I wasn't ready to begin applying the annotations yet. Everything broke after the `helm install` so I didn't get to that part.

Can you clarify what needs to happen with port 8080 on the master nodes? You're saying that needs to be opened up to the worker nodes? Shouldn't all node to master API requests go through port 443? I feel like I'm missing something here.

It's also my understanding that customers don't have access to change the open ports in the GKE master plane. If that's the case, would it be impossible to run the vault injector in GKE?

Regarding the last two pieces of connectivity, both my pods and master api can connect to vault just fine. I set up the Kubernetes Authentication method and I was able to connect to vault just fine from inside of my pods.

**Comment by tvoran** [comment]
> Can you clarify what needs to happen with port 8080 on the master nodes? You're saying that needs to be opened up to the worker nodes? Shouldn't all node to master API requests go through port 443? I feel like I'm missing something here.

The injector's mutating webhook service listens on port 8080, and you're right, I think our docs have the direction the wrong way; the master nodes need to be able to connect to the injector web service, so you may need to add firewall rules: https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules

**Comment by bazhip** [comment]
That works!! Adding a firewall rule from the masters to the worker nodes on 8080 did the trick.

**Comment by tvoran** [comment]
Closing now things seem to be working, and the docs are updated.
