### ISSUE TITLE
service_registration lines are missing a colon

### ISSUE THREAD

**Issue by todd-dsm** [hashicorp/vault-helm#370]
Lines 453 an 476 in values.yaml need to be updated to include the colon `:`.

```bash
service_registration "kubernetes" {}     # <- fail
service_registration "kubernetes": {}    # <- pass
```

[example](https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L453)

**To Reproduce**
1. Install chart: `helm install vault hashicorp/vault --values=values.yaml`
2. helm errors

**Comment by tvoran** [comment]
Hi @todd-dsm, I don't think adding a colon there is valid HCL. Can you share your values.yaml, and the helm errors you're getting?

**Comment by todd-dsm** [comment]
actually, I think you're right. I filed this late at night: brainmush. 

closing issue
