### ISSUE TITLE
injector-mutating-webhook.yaml requires sideeffects:None to be specified explicitly

### ISSUE THREAD

**Issue by mailhari** [hashicorp/vault-helm#377]
Here is the sequence:
1) Just taken (https://github.com/hashicorp/vault-helm/blob/master/templates/injector-mutating-webhook.yaml) alone for simplicity
cat /tmp/test.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: test123
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault-4
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: vault.hashicorp.com
    clientConfig:
      service:
        name: vault-4-agent-injector-svc
        namespace: my-ns
        path: "/mutate"
      caBundle:
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
2) kubect create -f /tmp/test.yaml
3) kubectl describe mutatingwebhookconfiguration test123 | head -n 10
kubectl describe mutatingwebhookconfiguration test123  | head -n 10
Name:         test123
Namespace:
Labels:       app.kubernetes.io/instance=vault-4
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault-agent-injector
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1
Kind:         MutatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2020-08-25T17:00:15Z
...
  Side Effects:     Unknown

We can see the APIVersion changed from v1beta1 to v1. Because of this, when I take a copy of the config from K8s server and recreate with differen name, K8s says Unknown is unsupported because of v1. So as a workaround I have to specify Sideeffects:None in https://github.com/hashicorp/vault-helm/blob/master/templates/injector-mutating-webhook.yaml

I dont know if it is K8s feature to change the API version. Since customer uses the chart from the github, I request you to see if this can be done in your chart? Or please let us know how to we handle this scenario.

**Comment by jasonodonnell** [comment]
Hi @mailhari, this is not a bug, K8s is converting it because you're requesting it to.  This should give you better results:

```bash
$ kubectl get mutatingwebhookconfigurations.v1beta1.admissionregistration.k8s.io test123 -o yaml
```

Also if you're interested in the deployment files for Vault Agent Injector alone, see the Vault K8s repo: https://github.com/hashicorp/vault-k8s/tree/master/deploy.

**Comment by hariharanrbn** [comment]
Thanks @jasonodonnell .

_K8s is converting it because you're requesting it to_
Can I know which part of the mutating config is requesting this conversion?

**Comment by jasonodonnell** [comment]
@hariharanrbn `kubectl describe mutatingwebhookconfiguration test123 | head -n 1` is defaulting to v1 (beta is deprecated on newer versions of K8s but still available for backwards compatibility.

**Comment by hariharanrbn** [comment]
Thanks again. I am closing this issue.

**Comment by mailhari** [comment]
Thanks again. I am closing this issue.
