### ISSUE TITLE
Allow also yaml configuration for nodeSelector, tolerations and affinities

### ISSUE THREAD

**Issue by FWest98** [hashicorp/vault-helm#380]
Similar to #272 (and somewhat also #213 ), it would be great to add support for using yaml instead of a string to configure the tolerations, affinity, and nodeSelector for the various components (injector, server). This would also be in line with how this is done in many other popular charts (which then ties in to #55 ).

**Comment by jasonodonnell** [comment]
I believe these are all supported, so closing this ticket.

**Comment by erks** [comment]
https://github.com/hashicorp/vault-helm/blob/dcb4b102835d1c9911cfc9a47fb9bfc2084ffdbf/templates/_helpers.tpl#L216 I don't see these fields supporting YAML yet on master. We still need to use string here. Can you reopen?

**Comment by FWest98** [comment]
I am not sure if I see what was changed in this. According to the docs all `nodeSelector`, `tolerations`, and `affinities` fields still require a multiline string instead of a yaml object. A quick look into the code reveals no clues that this has changed.

Could you maybe clarify what you changed to incorporate this?

**Comment by jasonodonnell** [comment]
My apologies, just misremembering. We added YAML support for a lot of other configurables, but missed these. We'll get these added.

**Comment by benashz** [comment]
Fixed in #565
