### ISSUE TITLE
Helm v3.3.0 linting declares "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" deprecated.

### ISSUE THREAD

**Issue by patrickstump** [hashicorp/vault-helm#390]
**Describe the bug**
When using the lates version of helm v3.3.0 and linting the helm chart the error below is received and causes linting (and our pipeline) to fail.
```
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting vault
[ERROR] templates/server-clusterrolebinding.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
```
**To Reproduce**
1. Install the latest version of helm 
    - our version ```version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}```

2. ```helm repo add hashicorp https://helm.releases.hashicorp.com```
3.  ```helm repo update```
4. ```helm pull hashicorp/vault --untar```
5. ```helm lint vault```

This will result in the following error:
```
$ helm lint vault
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting vault
[ERROR] templates/server-clusterrolebinding.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
```

**Expected behavior**
The helm linter should return without error.

**Environment**
* Kubernetes version:  NA 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): NA
  * Other configuration options or runtime services (istio, etc.): NA
* vault-helm version: 
```
helm show chart hashicorp/vault
apiVersion: v2
appVersion: 1.5.2
description: Official HashiCorp Vault Chart
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
keywords:
- vault
- security
- encryption
- secrets
- management
- automation
- infrastructure
name: vault
sources:
- https://github.com/hashicorp/vault
- https://github.com/hashicorp/vault-helm
- https://github.com/hashicorp/vault-k8s
version: 0.7.0

```

Chart values:

None: just the linting command

**Additional context**
None

**Comment by jasonodonnell** [comment]
Fixed via #395
