### ISSUE TITLE
Setup HOST_IP for use for secrets engines

### ISSUE THREAD

**Issue by BrysonMcI** [hashicorp/vault-helm#403]
Hey all, I'm currently setting up a consul + vault cluster. I am using consul as the storage backend, but I also want it to be a secret engine. You can use this handy configuration when defining the storage backend `address = "HOST_IP:8500"` and sed replaces it with the host IP so you can talk to a local consul agent. Unfortunately I can't find an easy way to get the same thing when defining a secret engine. I assume I will need some way to get an address to resolve to HOST_IP. This would allow me to safely keep all my connections between vault and consul over the localhost (as recommended by the secrets engine guide)

**Describe the solution you'd like**
I would either like to be able to provide in my values.yaml a configuration of [HostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) so I can set HOST_IP to spec.hostIP or setup the /etc/hosts in the container with HOST_IP at startup.

**Describe alternatives you've considered**
I tried doing this with a postStart hook, but vault user can not modify the /etc/hosts. I think this might be possible by sharing an /etc/hosts from a sidecar container which I define under extraContainers, but I am not sure

**Comment by lawliet89** [comment]
I think this can be supported by adding a "generic" extra environment specification for the `StatefulSet` pods to make use of the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) to get the Host IP address.

**Comment by BrysonMcI** [comment]
HOST_IP is already in the environment, unfortunately you can't use an environment variable as your address in a secrets engine (for example it just says it can't resolve $HOST_IP).

**Comment by lawliet89** [comment]
My bad. I didn't realise that.
