### ISSUE TITLE
Add ingress support on Helm Chart Configuration

### ISSUE THREAD

**Issue by yrosaguiar** [hashicorp/vault-helm#42]
We need the ingress support on helm installation.

Ex: Helm Configuration

| `ingress.enabled`                        | enable ingress                                                    | `false`                   |
| `ingress.web.host`                       | hostname for the webserver ui                           | ""                        |
| `ingress.web.path`                       | path of the werbserver ui (read `values.yaml`)   | "/ui"                    |
| `ingress.web.annotations`           | annotations for the web ui ingress                      | `{}`

**Comment by jasonodonnell** [comment]
Hi @yrosaguiar!

This is a feature we're looking to support soon.  As such I will leave this issue open to track the feature.

**Comment by yrosaguiar** [comment]
Thanks @jasonodonnell 

I'll work on this.
Thanks.

**Comment by jasonodonnell** [comment]
This feature has been merged and is being released in 0.2.0.  Closing.

**Comment by yrosaguiar** [comment]
Nice
