### ISSUE TITLE
Configuration option to apply labels to agent-injector

### ISSUE THREAD

**Issue by logileifs** [hashicorp/vault-helm#427]
**Is your feature request related to a problem? Please describe.**
I need to apply labels to the vault-agent-injector so it can bypass some network policies, currently there is no option in the helm chart to assign labels to it.

**Describe the solution you'd like**
Something like the extraLabels option for the server block would be good enough

**Describe alternatives you've considered**
I don't really know of any alternatives other than disabling the network policies and compromising security in the cluster

**Additional context**
Screenshot of agent-injector failing to start when network policies are in place
<img width="1518" alt="Screenshot 2020-12-07 at 14 01 03" src="https://user-images.githubusercontent.com/2317815/101359766-a6d19380-3894-11eb-8fe4-85148a909442.png">

**Comment by jasonodonnell** [comment]
Fixed in #428
