### ISSUE TITLE
Set `replica` count for Agent Injector Pods.

### ISSUE THREAD

**Issue by echoboomer** [hashicorp/vault-helm#432]
**Is your feature request related to a problem? Please describe.**
Is it possible to add the ability to set `replica` count for the Agent Injector `Pods`? I've noticed during cluster upgrades it's possible for evicted `Pods` to start without the shared volume mount when using the injector functionality. Running more than a single replica could help here, but I'm unsure if this was done by design. In the chart, this is currently hardcoded at `1`.

**Describe the solution you'd like**
The ability to run the injector `Pods` in high availability.

**Describe alternatives you've considered**
N/A

**Additional context**
I've contributed to this repository before so I'm happy to open a PR, but I wanted to check and see if there was a reason it was done like this. I apologize if this is documented elsewhere and I missed it.

**Comment by jasonodonnell** [comment]
Hi @echoboomer, thanks for opening an issue. There is a bug with the injector auto-tls that prevents us from exposing the replica config, but we have a solution coming for that very soon (being finalized now), so we'll be adding that once we push the newest version of Vault K8s.
