### ISSUE TITLE
Need distinct Labels for ha Service templates

### ISSUE THREAD

**Issue by ryan-dyer-sp** [hashicorp/vault-helm#445]
**Is your feature request related to a problem? Please describe.**
The existing ha Service templates all use the same labels 
```
kgs --show-labels
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                   AGE     LABELS
vault            ClusterIP   100.69.5.110     <none>        8200/TCP,8201/TCP                                                         4d18h   app.kubernetes.io/instance=vault,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=vault,helm.sh/chart=vault-0.9.0
vault-active     ClusterIP   100.66.213.128   <none>        8200/TCP,8201/TCP                                                         4d18h   app.kubernetes.io/instance=vault,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=vault,helm.sh/chart=vault-0.9.0
vault-internal   ClusterIP   None             <none>        8200/TCP,8201/TCP                                                         4d18h   app.kubernetes.io/instance=vault,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=vault,helm.sh/chart=vault-0.9.0
vault-standby    ClusterIP   100.65.135.194   <none>        8200/TCP,8201/TCP                                                         4d18h   app.kubernetes.io/instance=vault,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=vault,helm.sh/chart=vault-0.9.0
vault-ui         ClusterIP   100.71.113.210   <none>        8200/TCP                                                                  4d18h   app.kubernetes.io/instance=vault,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=vault-ui,helm.sh/chart=vault-0.9.0
```
Due to this, there is no way for a ServiceMonitor for prometheus to scrape the endpoints just once.  Each vault service gets scraped; and we dont have any use case for this as the metrics all point to the same 3 pods.

**Describe the solution you'd like**
Distinct app.kubernetes.io/component (or something similar) in order to be able to filter specific services so that prometheus will only scrape a specific service, not all 4 (app.kubernetes.io/name=vault).

**Additional context**
Am happy to submit PR with changes if someone just tells me what label to use.  I suggested component, but I dont entirely feel thats an accurate label either.  perhaps actually using app.kubernetes.io/name to match the service name would be appropriate?

**Comment by tvoran** [comment]
I think more labels were added in #772; I see `vault-active` has `vault-active: true` and `vault-internal` has `vault-internal: true`.

Since this was opened for an old version of the chart, I'm going to close this for now, but do let us know if you're still running into issues with prometheus.
