### ISSUE TITLE
Upgrade the Ingress Api versions to accomodate the v1

### ISSUE THREAD

**Issue by rokarajan** [hashicorp/vault-helm#468]
**Describe the bug**
Upon deploying vault using helm chart in kubernetes version 1.19 came across the message below so wnated to flag if you can accomodate the new api versions for ingress.

W0316 10:18:29.729348       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0316 10:18:29.936108       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**To Reproduce**
1. Install vault using helm chart in kubernets version 1.19

**Expected behavior**
As per this documentation: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
upgrade ingress with networking.k8s.io/v1 

**Environment**
* Kubernetes version: 
EKS 1.19

Chart version:
.0.9.1 app version 1.6.2
```yaml
# Be sure to scrub any sensitive values!
```

**Comment by tony-kerz** [comment]
https://github.com/hashicorp/vault-helm/pull/483

**Comment by tvoran** [comment]
I believe this has been addressed in #590, thanks.
