### ISSUE TITLE
Injector deployment needs to support hostNetwork

### ISSUE THREAD

**Issue by paulwitt** [hashicorp/vault-helm#470]
**Describe the bug**
The injector service does not work in EKS when using a 3rd party CNI

**To Reproduce**
1. Install EKS
2. Replace AWS-CNI with Weave.net
3. Install chart
4. Create a pod that needs to be injected with the sidecar
5. Webhook fails because the apiserver can't reach the injector service

See this issue for more details:  https://github.com/hashicorp/vault-k8s/issues/72

**Expected behavior**
Webhook to succeed

**Environment**
* Kubernetes version: EKS 1.15 using Weave.net CNI

**Comment by stealthHat** [comment]
man thank you so much, i was going crazy over this

**Comment by tvoran** [comment]
Looks like this was added in #471
