### ISSUE TITLE
helm install vault hashicorp/vault fails on k8s 1.11.10 cluster

### ISSUE THREAD

**Issue by wvivek** [hashicorp/vault-helm#476]
helm install vault hashicorp/vault
fails with the following error.

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1beta1.Webhook, ValidationError(MutatingWebhookConfiguration.webhooks[0]): unknown field "sideEffects" in io.k8s.api.admissionregistration.v1beta1.Webhook]

Made sure the admissionregistration api is enabled and using the correct version for 1.11.10 (v1beta1)
kubectl api-versions
admissionregistration.k8s.io/v1beta1

Please let me know what could be wrong .

**Comment by wvivek** [comment]
Can someone help on this?

**Comment by werdlv** [comment]
Same here

**Comment by tvoran** [comment]
Closing this since k8s 1.22 is now the earliest version supported, and `admissionregistration.k8s.io/v1beta1` [isn't served anymore](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22).
