### ISSUE TITLE
No possiblity to define imagePullSecrets in csi-deamonset.yaml

### ISSUE THREAD

**Issue by mehmetsalgar** [hashicorp/vault-helm#516]
**Describe the bug**
In the Helm Template  'https://github.com/hashicorp/vault-helm/blob/master/templates/csi-daemonset.yaml' there is no possiblity to define Image Pull Secret, as it is done in 'https://github.com/hashicorp/vault-helm/blob/master/templates/injector-deployment.yaml'

`      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}`

please introduce the same capability to 'csi-deamonset.yaml'

**To Reproduce**
1. helm install vault -n hashicorp/vault --set "injector.enabled=false" --set "csi.enabled=true"
2. If the docker registry protected with username/password, kubelet complains about missing Image Pull Secrets but is working for "injector.enabled=true" and "csi.enabled=false"

**Expected behavior**
csi deamonset Pod successfully created

**Environment**
* Kubernetes version: 1.17.9
  * Rancher 2.4.5
  
* vault-helm version: 0.11

Chart values:

```yaml
# Paste your user-supplied values here (`helm get values <release>`).
# Be sure to scrub any sensitive values!
```

**Comment by mehmetsalgar** [comment]
Pull Request if you need it...

[https://github.com/hashicorp/vault-helm/pull/517](Pull Request)

**Comment by tomhjp** [comment]
Thanks for raising and fixing this, it's hugely appreciated!
