### ISSUE TITLE
No possibility to configure tolerations for csi-deamonset.yaml

### ISSUE THREAD

**Issue by mehmetsalgar** [hashicorp/vault-helm#520]
**Describe the bug**
Even it is possible to configure tolerations for 'injesctor-deployment.yaml' and 'server-statefulset.yaml' same is not possible for 'csi-deployment.yaml'...

The consequense is any Worker Node that has a Taint, csi-deamonset.yaml ist not starting a Pod.

Pod Affinity configuration is also missing but I am not sure that is relevant for a DeamonSet.

**To Reproduce**
1. helm install vault-test hashicorp/vault --set "injector.enabled=false" --set "csi.enabled=true"
2. Worker Node with Taints are not getting csi-provider deployed

**Expected behavior**
Worker Node with Taints also get the csi-provider pods...

**Environment**
* Kubernetes version:  1.17.x
  * Rancher 2.4.5
* vault-helm version: 0.11.0

**Comment by mehmetsalgar** [comment]
PR if you need it

https://github.com/hashicorp/vault-helm/pull/521

**Comment by tvoran** [comment]
Thanks for the PR! Closed by #521
