### ISSUE TITLE
bug: helm cli version 3.2.0 is failing in vault-helm-test during bats unit test

### ISSUE THREAD

**Issue by anapsix** [hashicorp/vault-helm#539]
**Description of the bug**
In CircleCI, `vault-helm-test` image used for `test-unit` (`bats /helm-test/test/unit`) is using bugged version of Helm CLI client (`v3.2.0`) failling to render a valid templates. The same templates are passing bats unit tests and are rendering just fine using Helm CLI version `v3.6.0`.
Based on my tests going through every version of Helm CLI from `3.2.0` and up, the rendering issue is fixed in `v3.5.0`

Test Image:
- `docker.mirror.hashicorp.services/hashicorpdev/vault-helm-test:0.1.0`
- `docker.mirror.hashicorp.services/hashicorpdev/vault-helm-test@sha256:62b548d0b1bc07c2ec37133c60a441414c62fe3ee34692588f0c2c56be5d177e`
Link to the failing CI job: https://app.circleci.com/pipelines/github/hashicorp/vault-helm/810/workflows/9333e106-c18e-4331-848a-b20c576620c4/jobs/1061

**To Reproduce**
1. Clone my fork and switch to `allow-templated-extracontainers` branch (related to https://github.com/hashicorp/vault-helm/pull/536)
      ```sh
      git clone git@github.com:anapsix/vault-helm.git anapsix-vault-helm
      cd anapsix-vault-helm
      git checkout allow-templated-extracontainers
      ```
2. Pull the image CI is using for bats unit tests
      ```sh
      docker pull docker.mirror.hashicorp.services/hashicorpdev/vault-helm-test:0.1.0
      ```
3. Run bats unit test
      ```sh
      docker run \
        -it \
        --rm \
        -v "${PWD}:/src" \
        -w /src \
        docker.mirror.hashicorp.services/hashicorpdev/vault-helm-test:0.1.0 \
        bash -c 'helm version; bats /src/test/unit/server-statefulset.bats'
      ```
4. Observe the failure
5. Try again with new version of Helm
      ```sh
      docker run \
        -it \
        --rm \
        -v "${PWD}:/src" \
        -w /src \
        docker.mirror.hashicorp.services/hashicorpdev/vault-helm-test:0.1.0 \
        bash -c 'wget -O- https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz | tar -xzC /usr/local/bin --strip-components 1 linux-amd64/helm; helm version; bats /src/test/unit/server-statefulset.bats'
      ```

Please upgrade Helm version in `vault-helm-test` images used by CI to more recent version.

**Comment by tvoran** [comment]
Fixed by #543
