### ISSUE TITLE
Add support for Ingress networking.k8s.io/v1

### ISSUE THREAD

**Issue by velkovb** [hashicorp/vault-helm#587]
**Is your feature request related to a problem? Please describe.**
networking.k8s.io/v1 and networking.k8s.io/v1beta1 have different syntax and it is good to support the new version as the old one will get deprecated soon.

**Comment by jeroenlandheer** [comment]
We're having this as a blocking issue atm, we cannot use the helm chart on our K8s 1.22 cluster. (Ingress = v1beta)
