### ISSUE TITLE
Separate annotations per service

### ISSUE THREAD

**Issue by velkovb** [hashicorp/vault-helm#588]
**Is your feature request related to a problem? Please describe.**
Currently, the chart can accept only a single configuration for service annotations. My use case is that in AWS I want to present the active service via an NLB and that happens with the service annotations but as it set on all services, I get 3 NLBs deployed which is not what I want.

**Describe the solution you'd like**
Ability to specify annotations for specific service - active, standby, headless...

**Describe alternatives you've considered**
Present the service with an ingress.

**Comment by csabakollar** [comment]
enable ui, which creates a new service and you have the option: https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L693 active vault pod only. It will add an extra label to the label selector, so that ui will always go to the active pod.

**Comment by velkovb** [comment]
Thanks, that seems to be what I have been looking for but the UI part is what confused me. I assumed it is used only for exposing the UI and I was looking for the api and actually never looked into it.

**Comment by csabakollar** [comment]
np :)

**Comment by chris-ng-scmp** [comment]
This is an important feature, hope the PR can be reviewed soon...

**Comment by peikk0** [comment]
Same issue with the labels, which makes it impossible to use label selectors to select only one service.

**Comment by netflash** [comment]
This is related to my support ticket 101566, hopefully the ticket reference gives this issue an extra vote to get resolved faster.
