### ISSUE TITLE
Vault root rotation flow has a flaw !

### ISSUE THREAD

**Issue by pankaj-dahiya** [hashicorp/vault-helm#638]
**Describe the bug**
Vault root rotation flow has a flaw! The flaw is there when using helm charts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install a few apps with MySQL and vault.
2. MySQL (I am using latest bitnami/mysql) helm chart has root password set as Hello@123
3. Rotater root password of MySQL with the vault. (I do this via a k8s job running with the vault which will init, unseal and write policies inside the vault... obviously I have to use a job because we want automation!)
4. Delete the pod and let the new pod appear - Notice that the MySQL chart values.yaml still consists of root password as Hello@123. 
5. Mysql will keep restarting as it will try to run with root password as Hello@123

**Expected behaviour**
No idea, how to implement this, so that my MySQL will keep running while I use Vault rotate-root feature!

**Environment**
* Kubernetes version: 
* vault-helm version:
All versions latest - by the way, versions don't matter here.

**Comment by tomhjp** [comment]
Hi @pankaj-dahiya, for database backends, we recommend giving Vault its own user account. See here for further details: https://www.vaultproject.io/docs/secrets/databases#setup

In particular:

> It is highly recommended a user within the database is created specifically for Vault to use. This user will be used to manipulate dynamic and static users within the database. This user is called the "root" user within the documentation.

i.e. we do not recommend that Vault uses the actual database's root account.
