### ISSUE TITLE
Drop unneeded linux capabilities

### ISSUE THREAD

**Issue by OOTS** [hashicorp/vault-helm#663]
**Is your feature request related to a problem? Please describe.**
In our company, we want to enforce a policy where all applications running in K8s ought to drop as many Linux capabilities (in a container's security context) as possible. I would like to do that for Vault, but the [server-statefulset.yaml file](https://github.com/hashicorp/vault-helm/blob/main/templates/server-statefulset.yaml#L73) does not offer the option to do so.

**Describe the solution you'd like**
Ideally, the following piece of configuration in the server-statefulset.yaml file:
```
{{- if not .Values.global.openshift }}
securityContext:
  allowPrivilegeEscalation: false
{{- end }}
```
should be changed to:
```
securityContext:
  capabilities:
    drop: ["ALL"]
    {{- if not .Values.global.openshift }}
    allowPrivilegeEscalation: false
    {{- end }}
```
This would comply with the principle of least privilege, and harden Vault a little bit more.

I don't fully understand the situation with mlock, but from what I get, mlock is never used on K8s. If I'm mistaken, one should probably retain the `IPC_LOCK` capability.

**Describe alternatives you've considered**
Alternatively, the block shown above could be changed to:
```
{{- if or .Values.server.securityContext (not .Values.global.openshift) }}
securityContext:
  {{- if not .Values.global.openshift }}
  allowPrivilegeEscalation: false
  {{- end }}
  {{- if .Values.server.securityContext }}
    {{ tpl .Values.server.securityContext . | nindent $whatever }}
  {{- end }}
{{- end }}
```
This would allow more flexibility.

**Additional context**
References:
* [K8s Documentation for Security Contexts/Capabilities](https://kubernetes.io/docs/tasks/configure-pod-container/security-context)/#set-capabilities-for-a-container

I can send a PR if this change would be welcome.

**Comment by langecode** [comment]
Also could be nice if the security context structure was part of the values not "hard coded" inside of the templates (as also shown in the alternative here). This way it would be possible to adjust when deploying the chart - currently we have a policy in place requiring a drop of all privileges (as recommended in the restricted pod security standard: https://kubernetes.io/docs/concepts/security/pod-security-standards/

Not being able to adjust this forces us to do an exemption for this workload.

**Comment by OOTS** [comment]
By the way, the analogous thing should be done with:
- the Vault Agent Injector (the pods implementing the `MutatingWebhook`)
- the Init Containers and sidecars injected by the Vault Agent Injector
- the CSI daemonset.

**Comment by ChrisFraun** [comment]
I thought this might be related to the PR, which is ready for adding:
On Container Level:

- readOnlyRootFilesystem
- drop POSIX capabilities
- privileged

On POD level:

- fsGroup
- supplementalGroups

If needed, to not break downstream configurations.

Any thoughts? There is no movement on the PR so far, unfortunately..

**Comment by swenson** [comment]
It looks like https://github.com/hashicorp/vault-helm/pull/750 has been merged and includes the ability to customize the security context. I think this addresses this issue.

Thanks everyone!

**Comment by OOTS** [comment]
Hi @swenson ,

unfortunately, I disagree. The PR #750 allows me to configure the `securityContext`s in the `injector-deployment.yaml` file (which is good and a step in the right direction), but it still doesn't allow me to configure the [`securityContext` of the `vault` container in the `server-statefulset.yaml` file](https://github.com/hashicorp/vault-helm/blob/91b6c64f1fd8e23bb2fd1af6c897f6dd340a331e/templates/server-statefulset.yaml#L76), which is what this issue was about originally.

Can this issue please be re-opened until this is adressed properly?

Also, as pointed out in [my comment](https://github.com/hashicorp/vault-helm/issues/663#issuecomment-1108993916), it would be great if it were possible to configure the securityContext in the [`csi-daemonset.yaml`](https://github.com/hashicorp/vault-helm/blob/91b6c64f1fd8e23bb2fd1af6c897f6dd340a331e/templates/csi-daemonset.yaml#L43) and the `securityContext`s of the vault agent pods injected by the Vault Agent Injector.

**Comment by swenson** [comment]
Ah, you're right. My bad. I'll reopen and take more of a look.

**Comment by OOTS** [comment]
Thank you, @swenson.

**Comment by swenson** [comment]
Sorry about that @OOTS. I have https://github.com/hashicorp/vault-helm/pull/767 ready for review -- let me know is more what you had in mind.

**Comment by OOTS** [comment]
Thanks @swenson , looks pretty much like what I had in mind :+1:

**Comment by swenson** [comment]
Okay, *now* we should be able to support these use cases. :)
