### ISSUE TITLE
Test Helm Hook Pod should be more configurable

### ISSUE THREAD

**Issue by Iristyle** [hashicorp/vault-helm#665]
Depending on how Vault TLS certificates are created, it's possible for the [server-test Pod](https://github.com/hashicorp/vault-helm/blob/main/templates/tests/server-test.yaml) to not have access to the CA cert, preventing the tests from passing. This is causing CI failures for us because we wait for the Vault rollout to complete successfully. In production, we may see failing pods that frankly, we don't care about (since we have other checks to verify Vault is operational)

There are a number of features which would make the server-test Pod more useful:

* Ability to completely omit it from being generated
* Ability to specify additional environment variables (like `VAULT_CACERT` / `VAULT_CAPATH`) - see https://www.vaultproject.io/docs/commands#environment-variables
* Ability to mount extra volumes (i.e. with the CA cert)

Currently, the only workaround is a bit hacky and involves using Kustomize to delete the Pod resource. Unfortunately we only have this option in CI, but not in production, because we also use the KOTS tool from Replicated.

**Comment by mshaposhnik** [comment]
So, any option to disable that pod at all?
