### ISSUE TITLE
Remove image from global variables

### ISSUE THREAD

**Issue by tongpu** [hashicorp/vault-helm#68]
Because of the way global variables are implemented in this and the consul chart it is currently impossible to configure the consul chart as a dependency/subchart of the vault chart, because `global.image` with the value `vault:1.2.2` from the vault chart will also be rendered in the consul templates, because it too uses `global.image` for the configuration of the image version.

It is not recommended to use global variables in helm charts in this way and I would propose to switch to the normal way this is implemented in helm/charts, e.g.

```yaml
image:
  repository: vault
  tag: 1.2.2
```

The issue is tracked is also tracked in consul-helm: hashicorp/consul-helm#238

**Comment by jasonodonnell** [comment]
This is something we can look into, thanks for the report @tongpu !
