### ISSUE TITLE
Make publishNotReadyAddresses configurable in all cases?

### ISSUE THREAD

**Issue by avoidik** [hashicorp/vault-helm#685]
**Is your feature request related to a problem? Please describe.**

With the Kubernetes service discovery enabled I'd like to be able to configure `publishNotReadyAddresses` on Kubernetes service for Vault server as in [example](https://www.vaultproject.io/docs/configuration/service-registration/kubernetes#example-service)

**Describe the solution you'd like**

A few more options to be able to set `publishNotReadyAddresses`, for now only `ui` is supported

**Describe alternatives you've considered**

After patch, customized fork

**Additional context**

N/A

**Comment by isaidashev** [comment]
Are you planning to take any action?

**Comment by avoidik** [comment]
I was self reflecting justifying the real necessity of this feature flag, here is the PR

**Comment by tomhjp** [comment]
Released in 0.20.0 🎉
