### ISSUE TITLE
Old Kubernetes labels are used

### ISSUE THREAD

**Issue by rimusz** [hashicorp/vault-helm#7]
It should use https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

Latest versions of `helm` cli   generates the correct ones as well: `helm create some_chart`

**Comment by jasonodonnell** [comment]
Will fix, nice catch @rimusz !

**Comment by jasonodonnell** [comment]
Fixed via #8, closing.  Thanks!
