### ISSUE TITLE
gcpckms seal stanza adding incorrect resource names

### ISSUE THREAD

**Issue by mprinvale** [hashicorp/vault-helm#70]
0.1.2

Example stanza from values.yaml:
       seal "gcpckms" {
          project     = "my-project"
          region      = "us-east-1"
          key_ring    = "my-kr"
          crypto_key  = "vault-key"
       }

Expect resource name:
projects/my-project/locations/us-east1/keyRings/my-kr/cryptoKeys/vault-key

Actual resource name:
projects/my-project,/locations/us-east1,/keyRings/my-kr/cryptoKeys/vault-key

Above commas causing this error when installing vault:
Error parsing Seal configuration: failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = InvalidArgument desc = Resource name [projects/my-project,/locations/us-east1,/keyRings/my-kr/cryptoKeys/vault-key] does not match any known resource name pattern.

**Comment by jasonodonnell** [comment]
This seems unrelated to Vault Helm and should be reported in the main Vault repo: https://github.com/hashicorp/vault
