### ISSUE TITLE
injector "x509: certificate signed by unknown authority"  because auto-leader fails when old leader is in Terminated state

### ISSUE THREAD

**Issue by smurfralf** [hashicorp/vault-helm#704]
**Describe the bug**

With injectors.replicas=2, after injector pods are evicted from a kubernetes node and re-created on another node, kubernetes leaves the pod object there with STATUS=Terminated. The vault-agent-injector deploy creates new pods on some available node, but the logs of the new pods do not show that either becomes the leader. Given the analysis in the issue [Pods from same replicaset have different CA Bundles](https://github.com/hashicorp/vault-helm/issues/580), it looks like a change to the CA cert in the `vault-injector-certs`  is needed but not done.

**To Reproduce**
1. deploy helm chart  using env and values given at bottom.
2. verify that a simpletestpod can be deployed with init container created from injector annotations, then delete it.
3. drain the nodes the injector pods are running on (or create the cluster with preemptible nodes and wait for GKE to replace them).
4. use `kubectl get pods` after relocation of injector. Expect status of two pods to be `Terminated` and two to be `Running`.
5. try to deploy simpletestpod again. Output will be along the lines of

```bash
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"app.kubernetes.io/name":null,"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"...<snip>...}\n"},"labels":{"app.kubernetes.io/name":"simpletestpod"}}}
to:
Resource: "/v1, Resource=pods", GroupVersionKind: "/v1, Kind=Pod"
Name: "simpletestpod", Namespace: "default"
for: "pod.yml": Internal error occurred: failed calling webhook "vault.hashicorp.com": Post "https://vault-agent-injector-svc.cvc-vault.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
```

Judging from the comment in [https://github.com/hashicorp/vault-k8s/pull/271](https://github.com/hashicorp/vault-k8s/pull/271/files#diff-02d69310bf2e6ac092e361d5e966d9d7beade106a4c869805f8ea9b1cd81f4caR29):

 		// The Become() function blocks until this replica becomes the "leader",
		// by creating a ConfigMap with an OwnerReference. Another replica can
		// become the leader when the current leader replica stops running, and
		// the Kubernetes garbage collector deletes the vault-k8s-leader
		// ConfigMap.

If that comment is accurate, my guess is that the kubernetes garbage collector will not clean up the ConfigMap as expected because the pod still exists although it is not running. This hunch is supported by running

```bash
kubectl get configmap vault-k8s-leader -o yaml
```
where the results show the `ownerReference` is to one of the pods with Terminated status.

This problem is resolved by manually deleting the vault-k8s-leader config map, or by running `kubectl delete pod` for pods in Terminated status which causes them to be cleaned up.

**Expected behavior**

The certificate CA configured for the mutatingwebhookconfiguration vault-agent-injector-cfg should reflect the TLS cert being presented by the webhook's service. IE. the leader election should be based on what pods are running, not what pods are present.

**Environment**
* Kubernetes version: 1.21
  * Distribution or cloud vendor: GKE
  * Preemptible nodes
* vault-helm version: 1.19.0

Chart values:

```yaml
```hcl
global:
  enabled: true
  tlsDisable: false
injector:
  replicas: 2
  failurePolicy: Fail
  objectSelector:
    matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [simpletestpod]}
  podDisruptionBudget:
    maxUnavailable: 1
  strategy: |
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

**Additional context**

**Comment by tvoran** [comment]
It seems odd to me that the terminated Pods aren't being garbage collected. Is that something specific to preemptible nodes on GKE I wonder?

But as you surmised, if the injector pods are not being garbage collected (as mentioned in the [docs](https://www.vaultproject.io/docs/platform/k8s/injector/installation#multiple-replicas-and-tls)) then the built-in auto-tls isn't going to work for you with multiple replicas. I'd recommend using cert-manager or some other external cert management instead. 

There are a couple of examples up here:
- https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls-cert-manager
- https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls

**Comment by tirelibirefe** [comment]
> It seems odd to me that the terminated Pods aren't being garbage collected. Is that something specific to preemptible nodes on GKE I wonder?
> 
> But as you surmised, if the injector pods are not being garbage collected (as mentioned in the [docs](https://www.vaultproject.io/docs/platform/k8s/injector/installation#multiple-replicas-and-tls)) then the built-in auto-tls isn't going to work for you with multiple replicas. I'd recommend using cert-manager or some other external cert management instead.
> 
> There are a couple of examples up here:
> 
> * https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls-cert-manager
> * https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls

I followed the walkthrough [here ](https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls-cert-manager) and still getting the same error:

`Error creating: Internal error occurred: failed calling webhook "vault.hashicorp.com": failed to call webhook: Post "https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s": x509: certificate signed by unknown authority`

**Comment by smurfralf** [comment]
@tirelibirefe Our solution was not what @tvoran suggested so I can't say if that idea fixes the problem or not. We created a stable node pool with taints and assigned vault-injector to those. This stops them from being preempted on a regular basis.

I would recommend that you check via `curl -k -v` request to the vault endpoint that vault is actually using the certificate chain you think it is and that the CA of that train is correctly configured in your injector config.
