### ISSUE TITLE
runnuing multi vault pods on kubernetes  

### ISSUE THREAD

**Issue by msidd111** [hashicorp/vault-helm#71]
@jasonodonnell With standalone option Helm chart install a single pod and a single pVC.
Is there way we can have multiple vault pods with file storage so in a scenario when active vault becomes unavailable the secondary pod takes over. I understand storage is still a single volume but with multiple vault pods we can at least achieve HA form application side.

**Comment by billimek** [comment]
It may be possible to adapt the [transit unseal type](https://www.vaultproject.io/docs/configuration/seal/transit.html) for something like this.  I [wrote some instructions](https://github.com/billimek/k8s-gitops/tree/master/kube-system#vault-transit-unseal-server) for setting this up in my homelab cluster if you want to see an implementation that could be adapted.

Based on my experimentation, running a second transit vault server in the same cluster/failure domain may not be a great experience.

**Comment by billimek** [comment]
Ah, I think you are looking specifically at a way to have more resiliency with the vault server itself and not necessarily solving sealing issues.  My suggestion may not solve the ask, apologies!

**Comment by msidd111** [comment]
@billimek That's right. I am looking to have more resiliency with the vault server and file storage.

**Comment by jasonodonnell** [comment]
Hi @msidd111,

The file storage is not meant for HA deployments and should be used for a single instance of Vault.  That being said there's a new storage type that's currently in tech preview: raft.  This allows Vault to run in a cluster mode but uses a persistent volume for storage.  Note that this is a tech preview and is not suitable for production at this time.  Vault Helm is being adapted to support this storage type soon: https://github.com/hashicorp/vault-helm/pull/58

If resiliency is your requirement, you'll want an HA deployment (Vault Helm supports Consul out of the box for HA mode).

Just FYI, Vault Enterprise supports replication but Vault Helm does not yet support Vault Enterprise.
