### ISSUE TITLE
Cannot access chart repository

### ISSUE THREAD

**Issue by polRk** [hashicorp/vault-helm#717]
**Describe the bug**
Cannot instal/upgrade vault via helm

```
Error: failed to download "hashicorp/vault"
```

**To Reproduce**
```
helm upgrade -f vault/override-values.yaml -n vault vault hashicorp/vault
```

**Expected behavior**
All fine

**Environment**
* Kubernetes version:  1.22
  * DO
* vault-helm version: vault-0.19.0

Chart values:

```yaml
# Paste your user-supplied values here (`helm get values <release>`).
# Be sure to scrub any sensitive values!
```

**Additional context**
I'm in Belarus

**Comment by polRk** [comment]
https://helm.releases.hashicorp.com/index.yaml

```
403 ERROR

The request could not be satisfied.

The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
Generated by cloudfront (CloudFront)
Request ID: LN2HsQt_ycNMTAPoWU6qpMKu0mhfQK25hwynW3-nHuFwfynk23Qc7g==
```

Can you remove restriction for open source part, include helm charts?

**Comment by hsimon-hashicorp** [comment]
Because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.
Thank you for your understanding.

**Comment by polRk** [comment]
Can you move chart repository to open helm repo?
