### ISSUE TITLE
agent-injector shouldnt inject itself by default. 

### ISSUE THREAD

**Issue by tehlers320** [hashicorp/vault-helm#735]
**Describe the bug**
If/when all agents are down and you try to roll out an update. You cant, this is because the agent injects itself into itself. But its down.

**To Reproduce**
run helm template . 

you should see the disabled injection labels, but you dont.

https://github.com/hashicorp/vault-helm/blob/main/templates/injector-deployment.yaml#L9-L13

**Expected behavior**
agent never injects itself with itself.

**Environment**
* Kubernetes version: 
  * kubernetes
* vault-helm version: 0.20.0

Chart values:

```yaml
doesnt matter
```

**Comment by tvoran** [comment]
Hi there, this is something we've addressed recently with a different approach, by configuring the mutating webhook to ignore the injector pods by default: https://github.com/hashicorp/vault-helm/blob/45897a67fb48d8c809ea473ad5e1c0db35a5c23c/values.yaml#L135-L140
This is out in v0.20.1 of the chart.

And you're right, adding the `vault.hashicorp.com/agent-inject: false` label to the injector pods would achieve the same effect, and you should be able to set this via the [injector.extraLabels chart option](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#extralabels) today.
