### ISSUE TITLE
Unable to set custom annotations on SA for injector

### ISSUE THREAD

**Issue by monester** [hashicorp/vault-helm#740]
**Describe the bug**
We are using AWS auth for vault and to use vault injector I need to configure annotations on Service Account for vault injector.
It is not possible neither to set annotations on service accounts or use externally managed service account.
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
 
**To Reproduce**
- try adding annotations for injector SeviceAccount

**Expected behavior**
Able to add annotations for injector SA in values or use precreated service account.

**Environment**
* Kubernetes version: EKS 1.22
* vault-helm version: 0.20.1

Chart values:

```yaml
# Paste your user-supplied values here (`helm get values <release>`).
# Be sure to scrub any sensitive values!
```

**Additional context**

**Comment by tvoran** [comment]
Hi @monester, thanks for raising this issue! Indeed it does not look like the chart supports custom annotations for the injector's service account: https://github.com/hashicorp/vault-helm/blob/main/templates/injector-serviceaccount.yaml

I think this would be straightforward to add, similar to how we support custom annotations for the server's service account: https://github.com/hashicorp/vault-helm/blob/main/templates/server-serviceaccount.yaml#L13

**Comment by brunopadz** [comment]
Hi @monester, the maintainers just merged a PR I've opened implementing annotations for injectors Service Account. 

I recommend you to keep an eye for new releases. 😄

**Comment by tvoran** [comment]
Added in #753. Thanks all!
