### ISSUE TITLE
Helm install fails for vault-injector

### ISSUE THREAD

**Issue by kamaraj-muthupandian** [hashicorp/vault-helm#741]
**Describe the bug**
While installing the latest vault through helm , getting the following error.

Error: parse error at (vault/templates/_helpers.tpl:38): unclosed action

**To Reproduce**
1. Install chart
helm -n vault-system upgrade --install vault hashicorp/vault --set "injector.externalVaultAddr=https://vault.com" --set "injector.authPath=auth/dev-env"

Release "vault" does not exist. Installing it now.
Error: parse error at (vault/templates/_helpers.tpl:38): unclosed action

**Expected behavior**
Vault injector has to be installed

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor EKS 1.20

**Comment by tvoran** [comment]
Hi folks, I think that error is coming from an older version of Helm. As of 0.20.0 the chart requires Helm 3.6+: https://github.com/hashicorp/vault-helm/blob/main/README.md#prerequisites
