### ISSUE TITLE
Wrong Chart version in 0.1.2 release

### ISSUE THREAD

**Issue by KristapsT** [hashicorp/vault-helm#78]
Seems that ZIP for 0.1.2 release contains the Chart version 0.1.1, not 0.1.2.

To reproduce download 0.1.2 release ZIP: ﻿https://github.com/hashicorp/vault-helm/archive/v0.1.2.zip
Unzip and check Chart.yaml - it shows version 0.1.1.

Because of that, there are also no changes changes in this release that were introduced in 0.1.2, like ingress template.

**Comment by jasonodonnell** [comment]
Hi @KristapsT, aware of the issue with the Chart meta data in the 0.1.2, it will be resolved in 0.1.3.

Master contains a few features that have not been released yet, ingress being one of them.  Ingress was not part of 0.1.2 and you can expect it in 0.1.3!

**Comment by darnscott** [comment]
I'm having the same issue with the git tags. I'm deploying with helm-operator from ref: tags/v0.1.2 and it's deploying chart version 0.1.1.

**Comment by Aracki** [comment]
You can do `git clone https://github.com/hashicorp/vault-helm` while waiting for new release @KristapsT

**Comment by jasonodonnell** [comment]
Fixed in 0.2.0.
