### ISSUE TITLE
Vault agent injector sidecar Ephemeral Storage Limit propegates to all containers in pod when value is not set

### ISSUE THREAD

**Issue by 8-atje** [hashicorp/vault-helm#791]
**Describe the bug**
When installing Vault agent injector with helm chart 0.22.0 the sidecar will propegate the Ephemeral storage settings to other containers in the same pod if the container(s) does not include a value for the ephemeral storage limit or request. If the other container(s) have explicit set the ephemeral storage limit and request size they will not be affected. 
**To Reproduce**
1. Install chart 0.22
2. Deploy a pod without Ephemeral Storage Limit set and with Vault agent inject sidecar
3. Generate file(s) on filesystem exceeding the Vault agent injector sidecar ephemeral storage limit (default 128 MB)
4. Pod will get evicted when limit is exceeded

Other useful info to include: vault pod logs, `kubectl describe statefulset vault` and `kubectl get statefulset vault -o yaml` output

Downgrading to helm chart 0.21.0 reverts to expected behavior

**Expected behavior**
Containers in pod should be able to have no ephemeral storage limit and request set and not beeing affected by vault sidecar settings

**Environment**
* Kubernetes version: 
  * K8s v1.22.13 and 1.24.4
  * vault-helm version: 0.22.0
  * Vault Server external

Chart values:

USER-SUPPLIED VALUES:
injector:
  agentDefaults:
    cpuLimit: 500m
    cpuRequest: 250m
    memLimit: 128Mi
    memRequest: 64Mi
    template: map
  authPath: auth/xxxx-xxx
  externalVaultAddr: https://XXXXXX.XXXXX.XXX:XXXX

**Additional context**

**Comment by tomhjp** [comment]
Sorry for the breaking bug here - the breaking change was in https://github.com/hashicorp/vault-k8s/pull/360, and https://github.com/hashicorp/vault-k8s/pull/386 should hopefully address this. If all goes well in testing, we'll release a patch fix.

**Comment by 8-atje** [comment]
Thanks @tomhjp for fixing this. We have downgraded the helm deplyment until a new release is available.

**Comment by tvoran** [comment]
Hi folks, the fix was released in [vault-k8s v1.0.1](https://github.com/hashicorp/vault-k8s/releases/tag/v1.0.1), which was set as the default in [vault-helm v0.22.1](https://github.com/hashicorp/vault-helm/releases/tag/v0.22.1).
