### ISSUE TITLE
Make ephemeral storage of Agent sidecar injector configurable.

### ISSUE THREAD

**Issue by krishnadas-m** [hashicorp/vault-helm#797]
**Is your feature request related to a problem? Please describe.**
It is observed that the vault agent sidecar gets evicted due to the limit of ephemeral storage. It is currently defaulted to 128Mi and is not configurable via Helm-chart.

**Describe the solution you'd like**
If we can modify the injector-deployment template to template the AGENT_INJECT_EPHEMERAL_LIMIT value from values.yaml

**Describe alternatives you've considered**
We need to add/modify annotation on components to increase the limit which can be easily solved if we add the above mentioned capability on the vault helm-chart.

**Comment by tvoran** [comment]
Hi @krishnadas-m, this can be set via the helm chart currently with the [injector.extraEnvironmentVars](https://developer.hashicorp.com/vault/docs/platform/k8s/helm/configuration#extraenvironmentvars) option.

The next release of vault-k8s will also [stop setting a default ephemeral storage limit](https://github.com/hashicorp/vault-k8s/pull/386).

**Comment by krishnadas-m** [comment]
will pass additional env variables.
