### ISSUE TITLE
Update helm chart to AppVersion v1.12.0

### ISSUE THREAD

**Issue by FischerLGLN** [hashicorp/vault-helm#802]
Hi,

let me know, if anything further needs to be done to update the helm chart.

**Comment by tvoran** [comment]
We have a release planned soon, thanks! In the meantime, you're free to update the server image version in the chart values overrides since there aren't any changes needed in the chart for 1.12.0.

**Comment by hsimon-hashicorp** [comment]
As per @tvoran's response here, please keep your eyes peeled for an updated release and in the meantime use the work-around specified. I'm going to close this issue now as it's already planned. Thanks!
