### ISSUE TITLE
Add StatefulSet update strategy

### ISSUE THREAD

**Issue by dclark** [hashicorp/vault-helm#81]
The updatestrategy is currently set to OnDelete, allow for the values to define the strategy to be the alternative RollingUpdate.

**Comment by jasonodonnell** [comment]
Hi @dclark ,

The `OnDelete` strategy is on purpose to prevent the active node from being upgraded prior to standby nodes when using HA deployments.  RollingUpdates do not provide the coordination required to orchestrate this upgrade pattern.

**Comment by dclark** [comment]
@jasonodonnell understood. A feature to reviewed if there is a pod priority which can be applied which would affect the order of the RollingUpdate. So the standby nodes would be a higher priority allowing for the active node to be updated last.

**Comment by j-q-in-berlin** [comment]
I see this was resolved here: https://github.com/hashicorp/vault-helm/pull/172
