### ISSUE TITLE
Parsing Error at prometheus-prometheusrules.yaml

### ISSUE THREAD

**Issue by ShahSean** [hashicorp/vault-helm#812]
**Describe the bug**

Error: parse error at (vault/templates/prometheus-prometheusrules.yaml:1): unclosed action

**To Reproduce**
I'm pretty new to this area so unfortunately can't give as much info as I want.
But essentially there seems to be a parsing error on the `prometheus-prometheusrules.yaml` file.

**Comment by tomhjp** [comment]
What versions and commands are you using to reproduce please?

For versions:

```bash
helm version
helm show chart hashicorp/vault
```

Note that helm 3.6+ is required.

**Comment by ShahSean** [comment]
Thanks for your prompt response.

**Comment by michaelkoro** [comment]
What if i'm running helm through terraform? Is there a provider version constraint as well?

**Comment by tomhjp** [comment]
Thanks, that's a good question. I think it will be the first version of the provider that imported 3.6+ in that case, which looks to be 2.3.0: https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md#230-august-27-2021
