### ISSUE TITLE
Vault Environment Variable injector not working

### ISSUE THREAD

**Issue by iamaverrick** [hashicorp/vault-helm#816]
**Describe the bug**
The main issue is as follows.
We are trying to implement hasicorp vault to be the main source for all our secrets on our k8s cluster. We have configured vault to run inside k8s cluster, and that works perfectly. Now we are trying to switch each third-party OSS to make use of the secrets. The app we started to work with is [keycloak packaged by bitnami](https://github.com/bitnami/charts/tree/main/bitnami/keycloak). This helm chart, along with most of them, makes use of environment variables to configure their dependencies, such as, in this case, a PostgreSQL database. After reading the hasicorp vault documents for my use case i think is best to use the [Environment Variables Example](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples#environment-variable-example).

my Keycloak configure is as follows 

```
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/keycloak"
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {{`{{- with secret "database/creds/keycloak" -}}
      export KEYCLOAK_DATABASE_HOST=postgresql-url
      export KEYCLOAK_DATABASE_PORT=5432
      export KEYCLOAK_DATABASE_NAME=keycloak-db
      export KEYCLOAK_DATABASE_USER="{{ .Data.username }}"
      export KEYCLOAK_DATABASE_PASSWORD="{{ .Data.password }}"
    {{- end }}`}}
#  vault.hashicorp.com/agent-inject-command-db-creds: "/bin/sh -c . /vault/secrets/db-creds"
  vault.hashicorp.com/service: "https://vault.example.com"
  vault.hashicorp.com/role: "internal-app"

command: ['/bin/bash', '-c', ]
#command: ['/bin/bash', '-o', 'pipefail', '-c', ]
## @param args Override default container args (useful when using custom images)
##
args: ['source /vault/secrets/db-creds && /opt/bitnami/scripts/keycloak/run.sh']

```

In the args section, it states to use the entrypoint of the image so I grabbed that from [docker hub](https://hub.docker.com/layers/bitnami/keycloak/19.0.2-debian-11-r0/images/sha256-8fc37de7db98c539559396ea5d935bb6c8c727146a018e9751229fc00568976b?context=explore) .
after deploying the app I'm able to exec into the pod and if i run cat /vault/secrets/db-creds I'm able to see the EV vault secrets. but when i run printenv which shows all of the pods EV its not there. and this causes the pod to fail.

**To Reproduce**
1. Install vault helm chart
2. configure vault using the CLI, for PostgreSQL database creds, and k8s auth
3. deploy any service in this case we started with keycloak, configure the pods annotations for vault injector, and args as described in the docs
4. deploy the service using Environment variables from vault
5. 

Other useful info to include: vault pod logs, `kubectl describe statefulset vault` and `kubectl get statefulset vault -o yaml` output

**Expected behavior**
we are simply looking to use vault as a secret engine and provide the secrets as environment variables as described in the docs using the proper annotations. once a service is started the vault injector should inject the secrets necessary for the PostgreSQL to connect via EV.

**Environment**
* Kubernetes version: 
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8+vmware.1", GitCommit:"d797572df69c3951e4e8d495bf7720b594fd1c43", GitTreeState:"clean", BuildDate:"2022-03-21T23:17:28Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): Vmware V7 tanzu k8s cluster
  * Other configuration options or runtime services (istio, etc.): [Keycloak ](https://github.com/bitnami/charts/tree/main/bitnami/keycloak) App version 19.0.3, chart version 12.1.2
* vault-helm version: [Vault ](https://artifacthub.io/packages/helm/hashicorp/vault) App Version 1.12.1, helm version 0.22.0
please help or advise of a solution to this problem I've been stuck for weeks not trying to get this to work properly. thanks in advance

**Comment by tvoran** [comment]
Hi @iamaverrick, the environment variables will not show when running `printenv` because they’re only set for the entrypoint command (probably process 1). So to see what its environment variables are, exec into the container and `cat /proc/1/environ`. The output will be a bit squished but that'll show what the environment variables actually are.

In order to keep the container from crashing before you can inspect it, you may also want to replace run.sh with a sleep:

```
command: ['/bin/bash', '-c']
args: ['source /vault/secrets/db-creds && /bin/sleep 600']
```

I'm not sure the ``{{` `` are necessary in the template? Unless that's something to do with the deployment system, but something more like this should work directly with kubectl:

```
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {{- with secret "database/creds/keycloak" -}}
      export KEYCLOAK_DATABASE_HOST=postgresql-url
      export KEYCLOAK_DATABASE_PORT=5432
      export KEYCLOAK_DATABASE_NAME=keycloak-db
      export KEYCLOAK_DATABASE_USER="{{ .Data.username }}"
      export KEYCLOAK_DATABASE_PASSWORD="{{ .Data.password }}"
    {{- end }}
```

**Comment by iamaverrick** [comment]
Hello @tvoran, thank you for your prompt response.

The reason why we use `{{` ` ` is because we are using helm chart to deploy the software, and if we don't add that helm thinks its apart of a helm template and fails to deploy the pod. 

When i run cat /proc/1/environ as you described above, I'm able to see all correct environment variables and most importantly the username, and password has been injected with the proper values. so I'm confused as to what the pod is failing. if the proper EV are made available why is the pod failing?


**logs if using** 
```
command: ['/bin/bash', '-c', ]
## @param args Override default container args (useful when using custom images)
args: ['source /vault/secrets/db-creds && /opt/bitnami/scripts/keycloak/run.sh']
```
```
keycloak 20:32:34.41 INFO  ==> ** Starting keycloak **
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2022-12-07 20:32:42,522 WARN  [org.keycloak.services] (build-42) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2022-12-07 20:32:43,428 WARN  [org.keycloak.services] (build-42) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2022-12-07 20:32:49,126 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 10602ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized -cf=/opt/bitnami/keycloak/conf/keycloak.conf

ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Strict hostname resolution configured but no hostname setting provided
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

Process finished with exit code 0
```



**logs if using** 
```
command: ['/bin/bash', '-c', ]
## @param args Override default container args (useful when using custom images)
args: ['source /vault/secrets/db-creds && /opt/bitnami/scripts/keycloak/entrypoint.sh']
```
```
keycloak 20:36:48.10 
keycloak 20:36:48.10 Welcome to the Bitnami keycloak container
keycloak 20:36:48.10 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 20:36:48.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 20:36:48.11 


Process finished with exit code 0
```

After reading some issues on vault it seems like the environment variables are only available at entrypoint 
issues [186](https://github.com/hashicorp/vault-k8s/issues/186), [110](https://github.com/hashicorp/vault-k8s/issues/110), is this the case/

**Comment by tvoran** [comment]
Yeah the term "entrypoint" is a little overloaded; [this post](https://stackoverflow.com/questions/44316361/difference-between-docker-entrypoint-and-kubernetes-container-spec-command) explains it a little more as far as Dockerfile vs Kubernetes. 

In this case, the environment variables will only be set for whatever comes after `source /vault/secrets/db-creds && ` in the `args`. From looking at [bitnami/keycloak Dockerfile](https://github.com/bitnami/containers/blob/main/bitnami/keycloak/20/debian-11/Dockerfile#L52-L53), I suspect something like this may work better for you, since by default that container would effectively run `entrypoint.sh run.sh` on startup:

```yaml
command: ['/bin/bash', '-c', ]
## @param args Override default container args (useful when using custom images)
args: ['source /vault/secrets/db-creds && /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh']
```

**Comment by iamaverrick** [comment]
@tvoran 

I think the above solution somewhat works. Everything is working as expected as far as the injection is concerned. The app connects to the database correctly, but for some reason, after a minute, is stops with this error with no logs. Please keep in mind that before switching to vault i had everything working with a static username and password. so I'm guessing this has to be either with the args or something else.

```
rpc error: code = NotFound desc = an error occurred when try to find container "8b8835ebd8f107aa5b78d615e20c96491949c011c6be45786a1b9b93d2cb16f1": not found
Process finished with exit code 0
```

**Comment by miguelebf** [comment]
Hi, when im use command and args in yml its override dockerfile cmd command there are other way to apply source "/vault/secrets/comfig" command mantain cmd dockerfile command. thanks
