### ISSUE TITLE
Documentation - values.auditStorage.enabled is actually false by default

### ISSUE THREAD

**Issue by trexx** [hashicorp/vault-helm#820]
**Describe the bug**
As per documentation https://developer.hashicorp.com/vault/docs/platform/k8s/helm/configuration#auditstorage .values.auditStorage.enabled is apparently true by default. Upon looking at values.yaml, it is actually false. https://github.com/hashicorp/vault-helm/blob/v0.23.0/values.yaml#L679

**Environment**
* vault-helm version: 0.23.0

**Comment by tvoran** [comment]
Good spot! This is where the docs source lives: https://github.com/hashicorp/vault/blob/main/website/content/docs/platform/k8s/helm/configuration.mdx
