### ISSUE TITLE
Vault Agent Injector is getting Error updating MutatingWebhookConfiguration after upgrading EKS to 1.22

### ISSUE THREAD

**Issue by linhanhnguyen-gft** [hashicorp/vault-helm#824]
Description of the bug:
I have just upgraded the version of EKS from 1.21 to 1.22 with using Vault 1.6.2. After upgrading, I am getting the below error for hashicorp-vault-agent-injector and It can't start.
`2023-01-04T04:53:43.174Z [INFO]  handler: Starting handler..
Listening on ":8080"...
2023-01-04T04:53:43.188Z [INFO]  handler.auto-tls: Generated CA
2023-01-04T04:53:43.189Z [INFO]  handler.certwatcher: Updated certificate bundle received. Updating certs...
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
2023/01/04 04:53:48 http: TLS handshake error from 127.0.0.6:59373: no certificate available
2023/01/04 04:53:48 http: TLS handshake error from 127.0.0.6:33739: no certificate available
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
Error updating MutatingWebhookConfiguration: the server could not find the requested resource
2023/01/04 04:53:50 http: TLS handshake error from 127.0.0.6:34863: no certificate available
2023/01/04 04:53:50 http: TLS handshake error from 127.0.0.6:48877: no certificate available
2023/01/04 04:53:50 http: TLS handshake error from 127.0.0.6:60687: no certificate available`

Version
HC Vault: 1.6.2. Helm chart of Vault 0.9.1
EKS: 1.22

It was working fine at EKS 1.21 and only getting this issue after upgrading EKS to 1.22.

**Comment by thisgarryhas2rs** [comment]
I'm getting the same error when on GKE 1.22 with the same helm version (v0.9.1)

**Comment by Eli-Namogoo** [comment]
Hi,
any update on it?

**Comment by tvoran** [comment]
Hi folks, v0.9.1 of the chart is fairly old at this point and wasn't supported on kubernetes past 1.11. You should have better luck with a more recent version of the chart.
