### ISSUE TITLE
Upgrade from 0.5.0 to  0.23.0

### ISSUE THREAD

**Issue by bartoszkosciug** [hashicorp/vault-helm#839]
**Describe the bug**
During update the vault with helm from version 0.5.0 to 0.23.0 I got following error: 

```
Error: UPGRADE FAILED: [resource mapping not found for name: "vault-server-binding" namespace: "vault" from "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vault-agent-injector-cfg" namespace: "" from "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"
ensure CRDs are installed first]
```

**To Reproduce**
Steps to reproduce the behavior on k8s 1.22:
1. upgrade the chart from 0.5.0 to 0.23.0 
```
helm upgrade vault hashicorp/vault --version 0.23.0 --dry-run -n vault
```

**Environment**
* Kubernetes version:  1.22 EKS
* vault-helm version: 0.5.0

Chart values: default values

**Comment by OverStruck** [comment]
Run into same issue trying to install it on EKS 1.27 (K8s 1.27) - literally same error messages about CRDs
