### ISSUE TITLE
Stateful Image Pull Policy

### ISSUE THREAD

**Issue by cjstetson** [hashicorp/vault-helm#84]
Would it be possible to have the image pull policy not default and be configurable by helm chart.

Gives more control on how, when, why you might want to have new image pulled from repo.

**Comment by jasonodonnell** [comment]
I think this would be a good configurable, @cjstetson!   Open to pull requests to add this but will keep this issue open to track progress.

**Comment by jbialy** [comment]
I can tackle this one, will submit a PR!

**Comment by Alohabrow** [comment]
#92

**Comment by lliubaozhen-git** [comment]
goods
