### ISSUE TITLE
How to configure transit seal automatically

### ISSUE THREAD

**Issue by botzill** [hashicorp/vault-helm#86]
Hi.

It's confusing for me how to setup a `seal "transit" {` when we deploy the vault with helm chart. 

Any guides on how todo that?

I try to put this config

```
config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      seal "transit" {
        address            = "http://HOST_IP:8200"
        token              = "s.Qf1s5zigZ4OX6akYjQXJC1jY"
        disable_renewal    = "false"

        key_name           = "transit_key_name"
        mount_path         = "transit/"
        namespace          = "ns1/"
        tls_skip_verify    = "false"
      }
```

But I can't connect to to vault. Any guides to point me in the write direction?

Thx.

**Comment by billimek** [comment]
@botzill I wrote some instructions for my own gitops repo about doing just this (using an 'external' vault server as only an transit unsealer).  It may be helpful for your use-case: https://github.com/billimek/k8s-gitops/tree/master/kube-system#vault-transit-unseal-server

**Comment by botzill** [comment]
thx @billimek 

But in your case this `transit` unseal is a separate server and you are connecting to it from your k8s pod, right? 

Is there anyway to make this automatically in the same k8s cluster? 

I'm new to vault and still trying to understand and learn the basics. 

Thx.

**Comment by billimek** [comment]
I think it could be done such that a second vault server is deployed to the k8s cluster to act as a transit unseal vault server, however:

The second _transit_ vault server will itself become sealed whenever the pod is restarted via the k8s scheduler or some other reason.  This will result in the primary vault server not being able to auto-unseal itself while the transit vault server is sealed.

I experimented with this a bit by having two different vault servers act as transit servers for each-other and was dismayed to find that if they both restarted, everything became sealed.  Therefore running the vault unseal server externally made more sense (to me at least).

I do wonder if running vault or the vault unseal server in an HA mode would help mitigate the the issues I describe above.
