### ISSUE TITLE
Default `podAntiAffinity` prevents seamless upgrade of the Injector on a single-node Kubernetes cluster

### ISSUE THREAD

**Issue by vpedosyuk** [hashicorp/vault-helm#914]
**Describe the bug**
I was trying to upgrade vault-agent injector (without vault itself) on a single-node edge Kubernetes setup. However, it failed because of `podAntiAffinity` that by default expects a multi-node cluster for some reason. Maybe there's a reason to have that but it seemed to me a bit biased setting.

To workaround that I had to make other changes like deployment strategy: replace, adjust affinity rules, etc, which I'm not quite happy with - I just wanted to keep as minimal config as possible.

It'd be great to remove the default affinity rules for the injector if it's safe to do.

**To Reproduce**
1. Latest minikube
2. Install `injector` of an older version, let's say, `0.23.0`:
```sh
$ helm install vault-injector hashicorp/vault --version 0.23.0 --set 'injector.enabled=true' --set 'injector.externalVaultAddr=https://test.com'
NAME: vault-injector
LAST DEPLOYED: Fri Jun 16 15:32:24 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing HashiCorp Vault!

Now that you have deployed Vault, you should look over the docs on using
Vault with Kubernetes available here:

https://www.vaultproject.io/docs/


Your release is named vault-injector. To learn more about the release, try:

  $ helm status vault-injector
  $ helm get manifest vault-injector
```
3. make sure pods running:
```sh
$ kubectl get po
NAME                                             READY   STATUS    RESTARTS   AGE
vault-injector-agent-injector-6d75f6896d-czp58   1/1     Running   0          47s
```
4. upgrade to latest helm chart version:
```sh
$ helm upgrade vault-injector hashicorp/vault --version 0.24.1 --set 'injector.enabled=true' --set 'injector.externalVaultAddr=https://test.com'
Release "vault-injector" has been upgraded. Happy Helming!
NAME: vault-injector
LAST DEPLOYED: Fri Jun 16 15:37:28 2023
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
Thank you for installing HashiCorp Vault!

Now that you have deployed Vault, you should look over the docs on using
Vault with Kubernetes available here:

https://www.vaultproject.io/docs/


Your release is named vault-injector. To learn more about the release, try:

  $ helm status vault-injector
  $ helm get manifest vault-injector
```
5. observe that the upgrade failed and one of the pods got "pending" during rolling upgrade process:
```
$ kubectl get po
NAME                                             READY   STATUS    RESTARTS   AGE
vault-injector-agent-injector-65757bb469-pr7dm   0/1     Pending   0          42s
vault-injector-agent-injector-6d75f6896d-czp58   1/1     Running   0          5m47s
```
6. inspect why the pod is "pending":
```sh
$ kubectl describe po vault-injector-agent-injector-65757bb469-pr7dm
# .... long output
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  113s  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
```

**Expected behavior**
Successful rolling update of a pod.

**Environment**
```
😄  minikube v1.30.1 on Ubuntu 23.04
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
* vault-helm version: 0.24.1

Chart values:

```yaml
injector:
  enabled: true
  externalVaultAddr: https://test.com
```

**Comment by tomhjp** [comment]
Hi @vpedosyuk - thanks for raising this, and including lots of details. For your use-case, I would suggest just nulling out the affinity rules altogether:

```yaml
injector:
  enabled: true
  externalVaultAddr: https://test.com
  affinity: null
```

I considered changing the default to `preferred` instead of `required`, but I think overall it's nice to know that your deployment's "high availability" pod replicas actually are highly available and not all just on the same node :-) if something's gone wrong, it makes it pretty obvious because there's a pod that isn't running. And I agree that for the single-node use-case it is a bit annoying, I have tripped over that myself before, but I think it's also more normal to have multi-node Kubernetes clusters, so I feel like it's safest to leave it as-is for now.

**Comment by vpedosyuk** [comment]
@tomhjp, thanks for the answer. That absolutely makes sense to run HA deployment on different nodes. But the default configuration is not highly available, it's just a single replica. In my case, unfortunately, I was unaware that I was deploying the app with an affinity rule until I needed to upgrade the app - that's where things got messy.

> For your use-case, I would suggest just nulling out the affinity rules altogether

That's what I tried first but it didn't help. I just double-checked the "steps to reproduce" I posted but with a modified 4th step command:
```sh
helm upgrade vault-injector hashicorp/vault --version 0.24.1 --set 'injector.enabled=true' --set 'injector.externalVaultAddr=https://test.com' --set 'injector.affinity=null'
```

Here's the result:
```
$ k get po                                                      
NAME                                             READY   STATUS    RESTARTS   AGE
vault-injector-agent-injector-69b99dc87c-9jcb4   0/1     Pending   0          4m19s
vault-injector-agent-injector-6d75f6896d-psbnh   1/1     Running   0          5m5s
```

Indeed, `affinity: null` successfully nullified the affinity rule:
```sh
$ k get po vault-injector-agent-injector-69b99dc87c-9jcb4 -o jsonpath='{.spec.affinity}' | jq
$
```
But since the "old" pod still has the affinity rule:
```sh
$ k get po vault-injector-agent-injector-6d75f6896d-psbnh -o jsonpath='{.spec.affinity}' | jq
{
  "podAntiAffinity": {
    "requiredDuringSchedulingIgnoredDuringExecution": [
      {
        "labelSelector": {
          "matchLabels": {
            "app.kubernetes.io/instance": "vault-injector",
            "app.kubernetes.io/name": "vault-agent-injector",
            "component": "webhook"
          }
        },
        "topologyKey": "kubernetes.io/hostname"
      }
    ]
  }
}
```
the rolling upgrade process cannot be completed. I believe, this happens due to how Kubernetes works with "required" pod anti-affinities:
https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md#a-comment-on-symmetry

My report rather focuses on improving the Helm chart's user experience and making it more generic. However, I am open to whatever decision you believe is best. Thank you.
