### ISSUE TITLE
New version of helm chart not created since past few months

### ISSUE THREAD

**Issue by praveenjindal62** [hashicorp/vault-helm#915]
**Is your feature request related to a problem? Please describe.**
New version of helm chart is not released in past few month. We need some new features in helm chart which are already part of helm chart in main branch. Is it possible to create new release with the latest commit in `main` branch ?

**Comment by tomhjp** [comment]
Thanks for raising this - hopefully I can get a release out today if all goes smoothly with #916.

**Comment by hsimon-hashicorp** [comment]
Looks like https://github.com/hashicorp/vault-helm/releases/tag/v0.25.0 is out - is that sufficient? Thanks! :)
