### ISSUE TITLE
Service account enhancements needed for Kunbernetes v1.24

### ISSUE THREAD

**Issue by leathem1** [hashicorp/vault-helm#917]
**Is your feature request related to a problem? Please describe.**
With the new version of kubernetes (v1.24) the previous behavior of service accounts automatically getting created with secrets and tokens in that secret that dont expire has changed.  Can you update these vault templates to now create those for us?

**Describe the solution you'd like**
Have this helm chart create the long lived API tokens for Service accounts (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount)  since Kubernetes no longer does this for us.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tvoran** [comment]
Added in https://github.com/hashicorp/vault-helm/pull/923
