### ISSUE TITLE
Ability to scale replicas to zero

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/vault-helm#918]
We run multiple environments and would like to be able to simply set the replicas to "0" to reduce cost on testing environments when we are not actively using them.

Do you guys feel it's resonable to be able to do this in the chart of should I look into ways do do it outside the chart?

Thanks!

**Comment by therealjsie** [comment]
I've created a PR to change this behavior here: https://github.com/hashicorp/vault-helm/pull/943

**Comment by kschoche** [comment]
Fixed by #943
