### ISSUE TITLE
New version of helm chart

### ISSUE THREAD

**Issue by eufebius** [hashicorp/vault-helm#958]
New version of helm chart is not released in past few month. We need some new features in helm chart which are already part of helm chart in main branch. Is it possible to create new release with the latest commit in main branch? thx

**Comment by NeckBeardPrince** [comment]
I don't understand why we can't have at least a monthly update cadence. So far, we're three months behind.

**Comment by arslanbekov** [comment]
It's very, very unpleasant

**Comment by 0xmeyer** [comment]
I would be delighted to see a new release. When new release?

**Comment by NeckBeardPrince** [comment]
At this point, they have to be just doing it deliberately, right? Right?!

**Comment by tvoran** [comment]
Hi folks, apologies for the delay in getting the last release out. We’re looking into ways to improve the release process and cadence, and appreciate your patience!

**Comment by hsimon-hashicorp** [comment]
> At this point, they have to be just doing it deliberately, right? Right?!

Hello! Please take a moment to review our [Community Guidelines](https://www.hashicorp.com/community-guidelines) and please consider this your first warning. Our engineers are all human beings working hard to provide the best product they can. It is not acceptable to insinuate that anyone on our teams is actively trying to provide a bad experience for our users. I would ask for your patience and kindness in the future. Thank you.
